In [ ]:
print("TinyPhish Detector Project")
print("Python environment is ready!")

url = "https://example.com"

print("Sample URL:", url)
print("URL length:", len(url))
print("Contains @ symbol:", "@" in url)

TinyPhish Detector Project
Python environment is ready!
Sample URL: https://example.com
URL length: 19
Contains @ symbol: False

In [ ]:

#Step-1: TinyPhish Detector: First URL features

url = "http://example.com/login"

features = {
    "URL length": len(url),
    "Number of dots": url.count("."),
    "Contains @": int("@" in url),
    "Uses HTTPS": int(url.startswith("https://")),
    "Contains hyphen": int("-" in url),
    "Contains login": int("login" in url.lower())
}

print("URL:", url)
print("\nExtracted Features:")

for name, value in features.items():
    print(name, "=", value)

URL: http://example.com/login

Extracted Features:
URL length = 24
Number of dots = 1
Contains @ = 0
Uses HTTPS = 0
Contains hyphen = 0
Contains login = 1

In [ ]:

#Step-2: TinyPhish Detector: Standard feature extraction

def extract_features(url):
    url = url.strip()
    url_lower = url.lower()

    return [
        len(url),
        url.count("."),
        int("@" in url),
        int(url_lower.startswith("https://")),
        int("-" in url),
        int("login" in url_lower)
    ]


# Test the feature extraction function
test_url = "http://example.com/login"

features = extract_features(test_url)

feature_names = [
    "URL length",
    "Number of dots",
    "Contains @",
    "Uses HTTPS",
    "Contains hyphen",
    "Contains login"
]

print("Test URL:", test_url)
print("\nFeature values:")

for name, value in zip(feature_names, features):
    print(f"{name}: {value}")

print("\nNumber of features:", len(features))

Test URL: http://example.com/login

Feature values:
URL length: 24
Number of dots: 1
Contains @: 0
Uses HTTPS: 0
Contains hyphen: 0
Contains login: 1

Number of features: 6

In [ ]:

#Step:3 TinyPhish Detector: Understanding training labels

sample_data = [
    ("https://www.example.com", 0),
    ("http://example.com/login", 0),
    ("http://fake-login-example.invalid", 1),
    ("http://verify-account-example.invalid", 1)
]

print("Example training records:\n")

for url, label in sample_data:
    label_name = "Phishing" if label == 1 else "Legitimate"
    print("URL:", url)
    print("Label:", label, "-", label_name)
    print("-" * 40)

print("Total examples:", len(sample_data))
print("Legitimate examples:", sum(label == 0 for _, label in sample_data))
print("Phishing examples:", sum(label == 1 for _, label in sample_data))

Example training records:

URL: https://www.example.com
Label: 0 - Legitimate
----------------------------------------
URL: http://example.com/login
Label: 0 - Legitimate
----------------------------------------
URL: http://fake-login-example.invalid
Label: 1 - Phishing
----------------------------------------
URL: http://verify-account-example.invalid
Label: 1 - Phishing
----------------------------------------
Total examples: 4
Legitimate examples: 2
Phishing examples: 2

In [ ]:
# Step 4: Extract simple features from a URL

url = "https://www.example.com/login"

url_length = len(url)
dot_count = url.count(".")
hyphen_count = url.count("-")
has_https = int(url.startswith("https://"))
has_at_symbol = int("@" in url)

print("URL:", url)
print("URL length:", url_length)
print("Number of dots:", dot_count)
print("Number of hyphens:", hyphen_count)
print("Uses HTTPS:", has_https)
print("Contains @ symbol:", has_at_symbol)

URL: https://www.example.com/login
URL length: 29
Number of dots: 2
Number of hyphens: 0
Uses HTTPS: 1
Contains @ symbol: 0

In [ ]:
# Step 5: Create a reusable feature extractor

def extract_features(url):
    features = [
        len(url),
        url.count("."),
        url.count("-"),
        int(url.startswith("https://")),
        int("@" in url)
    ]

    return features


# Test the function
url = "https://www.example.com/login"

result = extract_features(url)

print("URL:", url)
print("Extracted features:", result)
print("Number of features:", len(result))

URL: https://www.example.com/login
Extracted features: [29, 2, 0, 1, 0]
Number of features: 5

In [ ]:
# Step 6: Test multiple URLs

test_urls = [
    "https://www.example.com",
    "http://example.com/login",
    "http://fake-login-example.invalid",
    "https://example.com/account/verify"
]

for url in test_urls:
    features = extract_features(url)

    print("URL:", url)
    print("Features:", features)
    print("-" * 40)

URL: https://www.example.com
Features: [23, 2, 0, 1, 0]
----------------------------------------
URL: http://example.com/login
Features: [24, 1, 0, 0, 0]
----------------------------------------
URL: http://fake-login-example.invalid
Features: [33, 1, 2, 0, 0]
----------------------------------------
URL: https://example.com/account/verify
Features: [34, 1, 0, 1, 0]
----------------------------------------

In [ ]:
# Step 7: Match URL features with labels

training_data = [
    ("https://www.example.com", 0),
    ("http://example.com/login", 0),
    ("http://fake-login-example.invalid", 1),
    ("http://verify-account-example.invalid", 1)
]

for url, label in training_data:
    features = extract_features(url)

    print("URL:", url)
    print("Features:", features)
    print("Label:", label)
    print("-" * 40)

URL: https://www.example.com
Features: [23, 2, 0, 1, 0]
Label: 0
----------------------------------------
URL: http://example.com/login
Features: [24, 1, 0, 0, 0]
Label: 0
----------------------------------------
URL: http://fake-login-example.invalid
Features: [33, 1, 2, 0, 0]
Label: 1
----------------------------------------
URL: http://verify-account-example.invalid
Features: [37, 1, 2, 0, 0]
Label: 1
----------------------------------------

In [ ]:
# Step 8: Separate features and labels

X = []
y = []

for url, label in training_data:
    X.append(extract_features(url))
    y.append(label)

print("Features (X):")
for row in X:
    print(row)

print("\nLabels (y):")
print(y)

print("\nNumber of records:", len(X))
print("Number of labels:", len(y))

Features (X):
[23, 2, 0, 1, 0]
[24, 1, 0, 0, 0]
[33, 1, 2, 0, 0]
[37, 1, 2, 0, 0]

Labels (y):
[0, 0, 1, 1]

Number of records: 4
Number of labels: 4

In [ ]:
# Step 9: Count the labels

legitimate_count = y.count(0)
phishing_count = y.count(1)

print("Total records:", len(y))
print("Legitimate URLs:", legitimate_count)
print("Phishing URLs:", phishing_count)

Total records: 4
Legitimate URLs: 2
Phishing URLs: 2

In [ ]:
# Step 10: Save the practice dataset

import pandas as pd

df = pd.DataFrame(training_data, columns=["url", "label"])

df.to_csv("practice_urls.csv", index=False)

print(df)
print("\nCSV file saved successfully!")

                                     url  label
0                https://www.example.com      0
1               http://example.com/login      0
2      http://fake-login-example.invalid      1
3  http://verify-account-example.invalid      1

CSV file saved successfully!

In [ ]:
import pandas as pd

df = pd.read_csv("phishing_features.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

df.head()

Dataset loaded successfully!
Dataset shape: (160064, 13)

Column names:
['url', 'label', 'url_length', 'num_dots', 'has_https', 'has_ip', 'num_subdirs', 'num_params', 'suspicious_words', 'tld', 'special_char_count', 'digits_count', 'entropy']

,url,label,url_length,num_dots,has_https,has_ip,num_subdirs,num_params,suspicious_words,tld,special_char_count,digits_count,entropy
0,http://forum.uk.securebankinggroup.com/107519/...,1,89,3,0,0,5,0,2,com,4,29,4.792985
1,http://b45042.com/fish/29,1,25,1,0,0,4,0,0,com,0,7,4.003856
2,http://bet73018.com/lottery/99,1,30,1,0,0,4,0,0,com,0,7,4.053236
3,https://logiin--metsa-autho.webflow.io/,1,39,2,1,0,3,0,0,io,3,0,4.150411
4,https://mettamasklogiiann.webflow.io/,1,37,2,1,0,3,0,0,io,0,0,4.100817

In [ ]:
print(df["label"].value_counts())

label
1    159244
0       820
Name: count, dtype: int64

In [ ]:
print(df.isnull().sum())

url                     0
label                   0
url_length              0
num_dots                0
has_https               0
has_ip                  0
num_subdirs             0
num_params              0
suspicious_words        0
tld                   821
special_char_count      0
digits_count            0
entropy                 0
dtype: int64

In [ ]:
print("Duplicate URLs:", df["url"].duplicated().sum())

Duplicate URLs: 0

In [ ]:
print("Unique labels:", sorted(df["label"].unique()))

Unique labels: [np.int64(0), np.int64(1)]

In [ ]:
url = df.loc[0, "url"]

print("URL:", url)
print("Actual URL length:", len(url))
print("Dataset URL length:", df.loc[0, "url_length"])

URL: http://forum.uk.securebankinggroup.com/107519/8af662/475d964a-0243-46bf-aefd-66da26254efa
Actual URL length: 89
Dataset URL length: 89

In [ ]:
actual = df["url"].str.len()

print("Mismatches:", (actual != df["url_length"]).sum())

Mismatches: 0

In [ ]:
actual_https = df["url"].str.lower().str.startswith("https://").astype(int)

print("HTTPS mismatches:", (actual_https != df["has_https"]).sum())

HTTPS mismatches: 0

In [ ]:
actual_dots = df["url"].str.count(r"\.")

print("Dot-count mismatches:", (actual_dots != df["num_dots"]).sum())

Dot-count mismatches: 0

In [ ]:
print(df[["url", "has_ip"]].sample(10, random_state=42).to_string(index=False))

                                                                                                                                                                                                     url  has_ip
https://docs.google.com/presentation/d/e/2PACX-1vQDZw9NrbHRNhlYpbDMh2TE_rBW44XTUEklQt-bJ0aKi1AXp0NAqZMw993B-iChXBQVfp0CbRzHBX4-/pub?start=false&amp;loop=false&amp;delayms=3000&amp;pli=1&amp;slide=id.p       0
                                                                                                                                                                             http://42.230.35.73:46886/i       1
                                                                                                                                                                           https://meta-navor.pages.dev/       0
                                                                                                                                                                        http://115.52.113.4:37206/bin.sh       1
                                             http://103.20.213.34:8080/Uploads/Uploads/ARYACORP%20POST%20FIXTURE/FIXTURE%20FOLDERS/MV%20YUE%20GUAN%20FENG-VISA%20BULK%20CPD%2021%20APRIL%202016/info.zip       1
                                                                                                          http://211.62.140.77/device/WICON-L-SERIAL-GSCAM/Latest/Wicon-L-Serial-gscam/resource/info.zip       1
          https://docs.google.com/presentation/d/e/2PACX-1vTuBX8GI2-IHioltCnwVHflIYJMGD7SMDC-aKxT6zIawOUGC2J4ldK5FGs6VSVatuFQ1NFI9KxTTEut/pub?start=false&amp;loop=false&amp;delayms=3000&amp;slide=id.p       0
                                                                                                                                                                  https://dewy.tu7q.online/0m6nvxypj6.sh       0
                                                                                                                                                                 https://b4.d5-en.ru/kp.check?t=jdp3tzd0       0
                                                                                                                                           http://120.48.25.153:9999/cs4.7-cn/third-party/winvnc.x86.dll       1

In [ ]:

from urllib.parse import urlparse
import ipaddress

def check_ip(url):
    host = urlparse(url).hostname
    try:
        ipaddress.ip_address(host)
        return 1
    except (ValueError, TypeError):
        return 0

actual_ip = df["url"].apply(check_ip)

print("has_ip mismatches:", (actual_ip != df["has_ip"]).sum())

has_ip mismatches: 109

In [ ]:

check = df.loc[actual_ip != df["has_ip"], ["url", "has_ip"]].copy()
check["actual_ip"] = actual_ip[actual_ip != df["has_ip"]]

print(check.head(10).to_string(index=False))

                                                    url  has_ip  actual_ip
http://176.65.149.4.ptr.pfcloud.network/bins/Demon.mpsl       1          0
        http://176.65.149.4.ptr.pfcloud.network/bins.sh       1          0
http://176.65.149.4.ptr.pfcloud.network/bins/Demon.m68k       1          0
http://176.65.149.4.ptr.pfcloud.network/bins/Demon.arm7       1          0
http://176.65.149.4.ptr.pfcloud.network/bins/Demon.arm5       1          0
 http://176.65.149.4.ptr.pfcloud.network/bins/Demon.sh4       1          0
http://176.65.149.4.ptr.pfcloud.network/bins/Demon.mips       1          0
 http://176.65.149.4.ptr.pfcloud.network/bins/Demon.x86       1          0
 http://176.65.149.4.ptr.pfcloud.network/bins/Demon.ppc       1          0
http://176.65.149.4.ptr.pfcloud.network/bins/Demon.arm6       1          0

In [ ]:

df["has_ip"] = actual_ip

print("Updated has_ip feature.")
print(df["has_ip"].value_counts())

Updated has_ip feature.
has_ip
0    82466
1    77598
Name: count, dtype: int64

In [ ]:

actual_digits = df["url"].str.count(r"\d")

print("Digit-count mismatches:",
      (actual_digits != df["digits_count"]).sum())

Digit-count mismatches: 0

In [ ]:

actual_slashes = df["url"].str.count("/")

print("Slash-count mismatches:",
      (actual_slashes != df["num_subdirs"]).sum())

Slash-count mismatches: 0

In [ ]:

actual_params = df["url"].str.count(r"\?") + df["url"].str.count("&")

print("Parameter-count mismatches:",
      (actual_params != df["num_params"]).sum())

Parameter-count mismatches: 0

In [ ]:

actual_special = df["url"].apply(
    lambda url: sum(url.count(c) for c in "-_%@=~")
)

print("Special-character mismatches:",
      (actual_special != df["special_char_count"]).sum())

Special-character mismatches: 0

In [ ]:

print("Label counts:")
print(df["label"].value_counts())

print("\nLabel percentages:")
print((df["label"].value_counts(normalize=True) * 100).round(2))

Label counts:
label
1    159244
0       820
Name: count, dtype: int64

Label percentages:
label
1    99.49
0     0.51
Name: proportion, dtype: float64

In [ ]:

print("BENIGN URLs (label 0):")
print(df[df["label"] == 0]["url"].head(10).to_string(index=False))

print("\nPHISHING URLs (label 1):")
print(df[df["label"] == 1]["url"].head(10).to_string(index=False))

BENIGN URLs (label 0):
       google.com
      youtube.com
    wikipedia.org
       github.com
stackoverflow.com
    microsoft.com
        apple.com
       openai.com
        adobe.com
   cloudflare.com

PHISHING URLs (label 1):
http://forum.uk.securebankinggroup.com/107519/8...
                         http://b45042.com/fish/29
                    http://bet73018.com/lottery/99
           https://logiin--metsa-autho.webflow.io/
             https://mettamasklogiiann.webflow.io/
                   http://bet73018.com/lottery/134
              https://metamasklogenies.webflow.io/
              https://mmettamaskilogin.webflow.io/
https://www.robiox.com.py/users/322503287968/pr...
             https://xbancobhd2025xxxxxxxxx.xo.je/

In [ ]:

import pandas as pd

new_df = pd.read_csv("Dataset.csv")

print("Dataset shape:", new_df.shape)
print("Column names:", new_df.columns.tolist())
print("\nFirst 5 rows:")
display(new_df.head())

Dataset shape: (116600, 26)
Column names: ['url', 'url_len', 'dom', 'dom_len', 'is_ip', 'tld', 'tld_len', 'subdom_cnt', 'letter_cnt', 'digit_cnt', 'special_cnt', 'eq_cnt', 'qm_cnt', 'amp_cnt', 'dot_cnt', 'dash_cnt', 'under_cnt', 'letter_ratio', 'digit_ratio', 'spec_ratio', 'is_https', 'slash_cnt', 'entropy', 'path_len', 'query_len', 'label']

First 5 rows:

,url,url_len,dom,dom_len,is_ip,tld,tld_len,subdom_cnt,letter_cnt,digit_cnt,...,under_cnt,letter_ratio,digit_ratio,spec_ratio,is_https,slash_cnt,entropy,path_len,query_len,label
0,https://www.rmit.edu.au/,24,rmit.edu.au,11,0,edu.au,6,1,17,0,...,0,0.708333,0.0,0.291667,1,3,3.709148,1,0,0
1,http://www.latrobe.edu.au/,26,latrobe.edu.au,14,0,edu.au,6,1,19,0,...,0,0.730769,0.0,0.269231,0,3,3.738149,1,0,0
2,https://www.cqu.edu.au/,23,cqu.edu.au,10,0,edu.au,6,1,16,0,...,0,0.695652,0.0,0.304348,1,3,3.609668,1,0,0
3,http://bond.edu.au/,19,bond.edu.au,11,0,edu.au,6,0,13,0,...,0,0.684211,0.0,0.315789,0,3,3.576618,1,0,0
4,http://www.csu.edu.au/,22,csu.edu.au,10,0,edu.au,6,1,15,0,...,0,0.681818,0.0,0.318182,0,3,3.503998,1,0,0

In [ ]:

print("Label counts:")
print(new_df["label"].value_counts())

print("\nLabel percentages:")
print((new_df["label"].value_counts(normalize=True) * 100).round(2))

print("\nMissing values in URL:", new_df["url"].isnull().sum())
print("Missing values in label:", new_df["label"].isnull().sum())
print("Duplicate URLs:", new_df["url"].duplicated().sum())

Label counts:
label
0    100000
1     16600
Name: count, dtype: int64

Label percentages:
label
0    85.76
1    14.24
Name: proportion, dtype: float64

Missing values in URL: 0
Missing values in label: 0
Duplicate URLs: 1369

In [ ]:

print("Unique labels:", sorted(new_df["label"].unique()))

new_df = new_df.drop_duplicates(subset="url").copy()

print("\nDataset after removing duplicate URLs:", new_df.shape)
print(new_df["label"].value_counts())

Unique labels: [np.int64(0), np.int64(1)]

Dataset after removing duplicate URLs: (115231, 26)
label
0    98641
1    16590
Name: count, dtype: int64

In [ ]:

original_new_df = pd.read_csv("Dataset.csv")

label_counts = original_new_df.groupby("url")["label"].nunique()
conflicts = label_counts[label_counts > 1]

print("URLs with conflicting labels:", len(conflicts))

URLs with conflicting labels: 0

In [ ]:

# 1. Check URL length
actual = new_df["url"].str.len()
print("URL length mismatches:", (actual != new_df["url_len"]).sum())

# 2. Check HTTPS
actual = new_df["url"].str.lower().str.startswith("https://").astype(int)
print("HTTPS mismatches:", (actual != new_df["is_https"]).sum())

# 3. Check digit count
actual = new_df["url"].str.count(r"\d")
print("Digit count mismatches:", (actual != new_df["digit_cnt"]).sum())

# 4. Check dot count
actual = new_df["url"].str.count(r"\.")
print("Dot count mismatches:", (actual != new_df["dot_cnt"]).sum())

# 5. Check hyphen count
actual = new_df["url"].str.count("-")
print("Hyphen count mismatches:", (actual != new_df["dash_cnt"]).sum())

# 6. Check underscore count
actual = new_df["url"].str.count("_")
print("Underscore count mismatches:", (actual != new_df["under_cnt"]).sum())

# 7. Check question-mark count
actual = new_df["url"].str.count(r"\?")
print("Question-mark mismatches:", (actual != new_df["qm_cnt"]).sum())

# 8. Check ampersand count
actual = new_df["url"].str.count("&")
print("Ampersand mismatches:", (actual != new_df["amp_cnt"]).sum())

# 9. Check slash count
actual = new_df["url"].str.count("/")
print("Slash count mismatches:", (actual != new_df["slash_cnt"]).sum())

# 10. Check URL and label missing values
print("Missing URLs:", new_df["url"].isnull().sum())
print("Missing labels:", new_df["label"].isnull().sum())

URL length mismatches: 0
HTTPS mismatches: 0
Digit count mismatches: 0
Dot count mismatches: 0
Hyphen count mismatches: 0
Underscore count mismatches: 0
Question-mark mismatches: 0
Ampersand mismatches: 0
Slash count mismatches: 0
Missing URLs: 0
Missing labels: 0

In [ ]:

from urllib.parse import urlparse
import ipaddress

# 1. Check equals-sign count
actual = new_df["url"].str.count("=")
print("Equals-sign mismatches:", (actual != new_df["eq_cnt"]).sum())

# 2. Check domain length
actual = new_df["dom"].str.len()
print("Domain-length mismatches:", (actual != new_df["dom_len"]).sum())

# 3. Check TLD length
actual = new_df["tld"].str.len()
print("TLD-length mismatches:", (actual != new_df["tld_len"]).sum())

# 4. Check IP-address feature
def check_ip(url):
    host = urlparse(url).hostname
    try:
        ipaddress.ip_address(host)
        return 1
    except (ValueError, TypeError):
        return 0

actual = new_df["url"].apply(check_ip)
print("IP-feature mismatches:", (actual != new_df["is_ip"]).sum())

# 5. Check label values
print("Unique labels:", sorted(new_df["label"].unique()))

# 6. Check duplicate URLs
print("Duplicate URLs:", new_df["url"].duplicated().sum())

Equals-sign mismatches: 0
Domain-length mismatches: 0
TLD-length mismatches: 14
IP-feature mismatches: 0
Unique labels: [np.int64(0), np.int64(1)]
Duplicate URLs: 0

In [ ]:

# Find rows where TLD length does not match
actual_tld_len = new_df["tld"].str.len()
mismatch = new_df[actual_tld_len != new_df["tld_len"]]

# Display the mismatched values
print(mismatch[["url", "tld", "tld_len"]].to_string(index=False))

                                                                          url tld  tld_len
                                http://202.194.232.100:8005/english/index.asp NaN        0
                                         https://www.ucatolica.edu.coeasyweb/ NaN        0
                  http://195.191.230.50/en/organisations/transport_institute/ NaN        0
http://212.49.120.102/index.php?option=com_content&task=view&id=54&Itemid=126 NaN        0
                                            http://112.126.90.210/guodaotong/ NaN        0
                                                      https://209.59.143.235/ NaN        0
                      http://159.253.211.183/our-hospitals/thornbury-hospital NaN        0
                                                 https://43.133.3.131/ETGate/ NaN        0
                                       http://132.232.170.50:9011/01cdfr.html NaN        0
                                                         http://103.99.210.5/ NaN        0
                                         http://184.70.150.18:60001/br01.html NaN        0
                                                        https://103.99.210.5/ NaN        0
                                                        https://43.153.99.18/ NaN        0
                                                      https://185.187.56.126/ NaN        0

In [ ]:

# 1. Check letter count
actual_letters = new_df["url"].str.count(r"[A-Za-z]")
print("Letter-count mismatches:",
      (actual_letters != new_df["letter_cnt"]).sum())

# 2. Inspect subdomain-count examples
print("\nSample subdomain values:")
print(new_df[["url", "dom", "subdom_cnt"]].head(10).to_string(index=False))

Letter-count mismatches: 6

Sample subdomain values:
                                          url            dom  subdom_cnt
                     https://www.rmit.edu.au/    rmit.edu.au           1
                   http://www.latrobe.edu.au/ latrobe.edu.au           1
                      https://www.cqu.edu.au/     cqu.edu.au           1
                          http://bond.edu.au/    bond.edu.au           0
                       http://www.csu.edu.au/     csu.edu.au           1
                http://research.mater.org.au/   mater.org.au           1
                       http://www.hri.org.au/     hri.org.au           1
                       https://www.epipsi.gr/      epipsi.gr           1
                     http://www.riotinto.com/   riotinto.com           1
http://www.arup.com/Global_locations/USA.aspx       arup.com           1

In [ ]:

# Find letter-count mismatches
actual_letters = new_df["url"].str.count(r"[A-Za-z]")
mismatch = new_df[actual_letters != new_df["letter_cnt"]]

print(mismatch[["url", "letter_cnt"]].to_string(index=False))

# Show the calculated counts
print("\nCalculated letter counts:")
print(actual_letters.loc[mismatch.index].to_list())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              url  letter_cnt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 https://гуманитарный-институт.рф          27
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             http://нииип-нзик.рф          15
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        https://музей-чайковский.рф/people/grnhu/          33
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  https://ufggfj.nh1do.cyou/ð¢ð§ððžð±.ð¡ð­ð¦ð¥          29
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  https://ufggfj.vj1zm.cyou/ð¢ð§ððžð±.ð¡ð­ð¦ð¥          29
https://duso.artmosaicstudio.shop/fclkv2/ch-de-dpp/?aff_id=push_aff_id&amp;aff_sub2=323&amp;aff_sub3=&amp;aff_sub4=&amp;aff_sub5=&amp;affiliate_id=1862&amp;c=%7C752&amp;cc=ch&amp;clickid=w1126c7cnaucs01638ln374d&amp;cpc=0.0&amp;id=w1126c7cnaucs01638ln374d&amp;isp=Sunrise+Upc+Gmbh&amp;k=ch-de-dpp&amp;keyword=ch-de-dpp&amp;lpc=1733126684533&amp;lptoken=170a336b12f884948494&amp;modifier=&amp;offer_id=752&amp;privacy=1Â®ion=Zurich&amp;s=1862&amp;source=&amp;src=&amp;tracker=surfadvance.com&amp;vid=IPQS_80&amp;view=IPQS_80&amp;oho=t5.linkloot.su&amp;currts=1733126684&amp;ptf=26934eb377001f66e37289a5c93fe284         371

Calculated letter counts:
[5, 4, 16, 19, 19, 370]

In [ ]:

from urllib.parse import urlparse

# Extract hostname from each URL
actual_host = new_df["url"].apply(
    lambda url: urlparse(url).hostname
)

# Compare hostname with stored domain
mismatch = actual_host.str.lower() != new_df["dom"].str.lower()

print("Domain mismatches:", mismatch.sum())
print("\nExamples:")
print(new_df.loc[mismatch, ["url", "dom"]].head(10).to_string(index=False))

Domain mismatches: 91955

Examples:
                                          url            dom
                     https://www.rmit.edu.au/    rmit.edu.au
                   http://www.latrobe.edu.au/ latrobe.edu.au
                      https://www.cqu.edu.au/     cqu.edu.au
                       http://www.csu.edu.au/     csu.edu.au
                http://research.mater.org.au/   mater.org.au
                       http://www.hri.org.au/     hri.org.au
                       https://www.epipsi.gr/      epipsi.gr
                     http://www.riotinto.com/   riotinto.com
http://www.arup.com/Global_locations/USA.aspx       arup.com
                        http://www.btplc.com/      btplc.com

In [ ]:
from urllib.parse import urlparse

# Extract hostname from each URL
actual_host = new_df["url"].fillna("").astype(str).apply(
    lambda url: (
        urlparse(url if "://" in url else "//" + url).hostname or ""
    ).lower().rstrip(".")
)

# Clean stored domains
stored_dom = new_df["dom"].fillna("").astype(str).str.lower().str.strip()

# Compare each hostname with its corresponding stored domain
matches = pd.Series([
    host == dom or host.endswith("." + dom)
    for host, dom in zip(actual_host, stored_dom)
], index=new_df.index)

# Ignore missing hostnames and domains
valid = (actual_host != "") & (stored_dom != "")

print("Domain suffix mismatches:", ((~matches) & valid).sum())

print("\nExamples of mismatches:")
print(
    new_df.loc[(~matches) & valid, ["url", "dom"]]
    .head(10)
    .to_string(index=False)
)

Domain suffix mismatches: 0

Examples of mismatches:
Empty DataFrame
Columns: [url, dom]
Index: []

In [ ]:
from urllib.parse import urlparse
import pandas as pd

# Extract hostnames and remove trailing dots
actual_host = new_df["url"].fillna("").astype(str).apply(
    lambda url: (
        urlparse(url if "://" in url else "//" + url).hostname or ""
    ).lower().rstrip(".")
)

# Clean stored domains
stored_dom = (
    new_df["dom"].fillna("").astype(str).str.lower().str.strip().str.rstrip(".")
)

# Compare hostname and domain row by row
matches = pd.Series(
    [
        host == dom or host.endswith("." + dom)
        for host, dom in zip(actual_host, stored_dom)
    ],
    index=new_df.index,
    dtype=bool
)

# Ignore rows with missing hostnames or domains
valid = actual_host.ne("") & stored_dom.ne("")

print("Domain suffix mismatches:", int(((~matches) & valid).sum()))

print("\nExamples of mismatches:")
print(
    new_df.loc[(~matches) & valid, ["url", "dom"]]
    .head(10)
    .to_string(index=False)
)

Domain suffix mismatches: 0

Examples of mismatches:
Empty DataFrame
Columns: [url, dom]
Index: []

In [ ]:
# Remove trailing dots from hostnames
actual_host = new_df["url"].apply(
    lambda url: urlparse(url).hostname
).str.lower().str.rstrip(".")

stored_dom = new_df["dom"].fillna("").str.lower().str.rstrip(".")

matches = pd.Series(
    [
        host == domain or host.endswith("." + domain)
        if host and domain else False
        for host, domain in zip(actual_host, stored_dom)
    ],
    index=new_df.index
)

print("Domain suffix mismatches:", (~matches).sum())

Domain suffix mismatches: 0

In [ ]:

# STEP 3: Extract simple URL features

import re
import ipaddress
from urllib.parse import urlparse

def extract_features(url):
    url = str(url)
    parsed = urlparse(url if "://" in url else "//" + url)
    host = parsed.hostname or ""

    try:
        ipaddress.ip_address(host)
        has_ip = 1
    except ValueError:
        has_ip = 0

    return [
        len(url),                          # URL length
        url.count("."),                    # Number of dots
        url.count("-"),                    # Number of hyphens
        int(url.lower().startswith("https://")), # HTTPS flag
        int("@" in url),                   # Contains @
        sum(c.isdigit() for c in url),     # Number of digits
        url.count("/"),                    # Number of slashes
        int(has_ip)                        # Host is an IP address
    ]

# Test with one safe-looking and one suspicious-looking URL
test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify"
]

for url in test_urls:
    print("\nURL:", url)
    print("Features:", extract_features(url))

URL: https://www.google.com
Features: [22, 2, 0, 1, 0, 0, 2, 0]

URL: http://192.168.1.1/login@verify
Features: [31, 3, 0, 0, 1, 8, 3, 1]

In [ ]:

# STEP 4: Extract features from the complete dataset

import pandas as pd

feature_names = [
    "url_length", "num_dots", "num_hyphens", "has_https",
    "has_at", "num_digits", "num_slashes", "has_ip"
]

X = pd.DataFrame(
    new_df["url"].apply(extract_features).tolist(),
    columns=feature_names,
    index=new_df.index
)

y = new_df["label"].astype(int)

print("Feature dataset shape:", X.shape)
print("Label dataset shape:", y.shape)

print("\nFirst 5 feature rows:")
print(X.head())

print("\nLabel counts:")
print(y.value_counts())

Feature dataset shape: (115231, 8)
Label dataset shape: (115231,)

First 5 feature rows:
   url_length  num_dots  num_hyphens  has_https  has_at  num_digits  \
0          24         3            0          1       0           0
1          26         3            0          0       0           0
2          23         3            0          1       0           0
3          19         2            0          0       0           0
4          22         3            0          0       0           0

   num_slashes  has_ip
0            3       0
1            3       0
2            3       0
3            3       0
4            3       0

Label counts:
label
0    98641
1    16590
Name: count, dtype: int64

In [ ]:
# Day 8, Step 8: Feature consistency test

test_urls = [
    "https://www.google.com",
    "example.com/path",
    "http://192.168.1.1/login",
    "http://192.168.1.1/login@verify",
    "HTTPS://Example.com/path"
]

for url in test_urls:
    print("\nURL:", url)
    print("Features:", extract_features(url))

URL: https://www.google.com
Features: [22, 2, 0, 1, 0, 0, 2, 0]

URL: example.com/path
Features: [16, 1, 0, 0, 0, 0, 1, 0]

URL: http://192.168.1.1/login
Features: [24, 3, 0, 0, 0, 8, 3, 1]

URL: http://192.168.1.1/login@verify
Features: [31, 3, 0, 0, 1, 8, 3, 1]

URL: HTTPS://Example.com/path
Features: [24, 1, 0, 1, 0, 0, 3, 0]

In [ ]:
url = "https://[2001:db8::1]/login"

print("URL:", url)
print("Features:", extract_features(url))

URL: https://[2001:db8::1]/login
Features: [27, 0, 0, 1, 0, 6, 3, 1]

In [ ]:

# STEP 5: Split the dataset (80% training, 20% testing)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining label counts:")
print(y_train.value_counts())

print("\nTesting label counts:")
print(y_test.value_counts())

Training samples: 92184
Testing samples: 23047

Training label counts:
label
0    78912
1    13272
Name: count, dtype: int64

Testing label counts:
label
0    19729
1     3318
Name: count, dtype: int64

In [ ]:

# STEP 6: Train the model

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = make_pipeline(
    StandardScaler(),
    LogisticRegression(class_weight="balanced", max_iter=1000, random_state=42)
)

model.fit(X_train, y_train)

print("Model training completed successfully!")

Model training completed successfully!

In [ ]:

# STEP 7: Evaluate Logistic Regression

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score
)

y_pred = model.predict(X_test)

print("Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(
    y_test, y_pred,
    target_names=["Benign", "Phishing"],
    digits=4
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 85.21 %

Classification Report:
              precision    recall  f1-score   support

      Benign     0.9816    0.8431    0.9071     19729
    Phishing     0.4926    0.9060    0.6382      3318

    accuracy                         0.8521     23047
   macro avg     0.7371    0.8745    0.7726     23047
weighted avg     0.9112    0.8521    0.8684     23047

Confusion Matrix:
[[16633  3096]
 [  312  3006]]

In [ ]:

# STEP 8: Train and evaluate a Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

tree_model = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

tree_model.fit(X_train, y_train)

tree_pred = tree_model.predict(X_test)

print("Decision Tree Classification Report:")
print(classification_report(
    y_test,
    tree_pred,
    target_names=["Benign", "Phishing"],
    digits=4
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, tree_pred))

Decision Tree Classification Report:
              precision    recall  f1-score   support

      Benign     0.9856    0.8874    0.9339     19729
    Phishing     0.5796    0.9231    0.7121      3318

    accuracy                         0.8925     23047
   macro avg     0.7826    0.9053    0.8230     23047
weighted avg     0.9272    0.8925    0.9020     23047

Confusion Matrix:
[[17507  2222]
 [  255  3063]]

In [ ]:
# TinyPhish: Python prediction test

test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify",
    "192.168.1.1/login",
    "HTTPS://Example.com/path",
    "example.com/path",
    "https://[2001:db8::1]/login"
]

for url in test_urls:
    features = extract_features(url)
    prediction = tree_model.predict([features])[0]
    label = "Phishing" if prediction == 1 else "Benign"

    print("URL:", url)
    print("Features:", features)
    print("Prediction:", int(prediction), "-", label)
    print()

URL: https://www.google.com
Features: [22, 2, 0, 1, 0, 0, 2, 0]
Prediction: 0 - Benign

URL: http://192.168.1.1/login@verify
Features: [31, 3, 0, 0, 1, 8, 3, 1]
Prediction: 0 - Benign

URL: 192.168.1.1/login
Features: [17, 3, 0, 0, 0, 8, 1, 1]
Prediction: 1 - Phishing

URL: HTTPS://Example.com/path
Features: [24, 1, 0, 1, 0, 0, 3, 0]
Prediction: 1 - Phishing

URL: example.com/path
Features: [16, 1, 0, 0, 0, 0, 1, 0]
Prediction: 0 - Benign

URL: https://[2001:db8::1]/login
Features: [27, 0, 0, 1, 0, 6, 3, 1]
Prediction: 1 - Phishing

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:

# STEP 9: Train and evaluate Random Forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

rf_model = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print("Random Forest Classification Report:")
print(classification_report(
    y_test, rf_pred,
    target_names=["Benign", "Phishing"],
    digits=4
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

Random Forest Classification Report:
              precision    recall  f1-score   support

      Benign     0.9869    0.8810    0.9310     19729
    Phishing     0.5681    0.9304    0.7054      3318

    accuracy                         0.8881     23047
   macro avg     0.7775    0.9057    0.8182     23047
weighted avg     0.9266    0.8881    0.8985     23047

Confusion Matrix:
[[17382  2347]
 [  231  3087]]

In [ ]:

# STEP 11: Measure Decision Tree model size

import joblib
import os

joblib.dump(tree_model, "phishing_tree_model.joblib")

size_bytes = os.path.getsize("phishing_tree_model.joblib")
size_kb = size_bytes / 1024
size_mb = size_bytes / (1024 * 1024)

print("Model file size:", size_bytes, "bytes")
print("Model file size:", round(size_kb, 2), "KB")
print("Model file size:", round(size_mb, 4), "MB")

if size_bytes < 1_000_000:
    print("PASS: Below 1 MB (decimal)")
else:
    print("FAIL: At least 1 MB")

Model file size: 74393 bytes
Model file size: 72.65 KB
Model file size: 0.0709 MB
PASS: Below 1 MB (decimal)

In [ ]:

# STEP 11A: Compare Decision Tree configurations

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
import pandas as pd

X_subtrain, X_val, y_subtrain, y_val = train_test_split(
    X_train, y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

results = []

for depth in [5, 10, 15]:
    for leaf in [5, 20]:
        candidate = DecisionTreeClassifier(
            max_depth=depth,
            min_samples_leaf=leaf,
            class_weight="balanced",
            random_state=42
        )

        candidate.fit(X_subtrain, y_subtrain)
        pred = candidate.predict(X_val)

        report = classification_report(
            y_val, pred,
            output_dict=True,
            zero_division=0
        )

        results.append({
            "max_depth": depth,
            "min_samples_leaf": leaf,
            "phishing_precision": report["1"]["precision"],
            "phishing_recall": report["1"]["recall"],
            "phishing_f1": report["1"]["f1-score"],
            "accuracy": report["accuracy"]
        })

results_df = pd.DataFrame(results)
print(results_df.round(4).to_string(index=False))

 max_depth  min_samples_leaf  phishing_precision  phishing_recall  phishing_f1  accuracy
         5                 5              0.5300           0.9228       0.6733    0.8711
         5                20              0.5297           0.9216       0.6727    0.8709
        10                 5              0.5676           0.9318       0.7055    0.8880
        10                20              0.5632           0.9341       0.7027    0.8862
        15                 5              0.5880           0.9205       0.7176    0.8957
        15                20              0.5862           0.9224       0.7168    0.8951

In [ ]:

# STEP 12: Train selected model and export to JSON

from sklearn.tree import DecisionTreeClassifier
import json
import os

final_model = DecisionTreeClassifier(
    max_depth=15,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42
)

# Train on the complete training set
final_model.fit(X_train, y_train)

# Export the learned tree
tree = final_model.tree_

tree_data = {
    "feature_names": feature_names,
    "children_left": tree.children_left.tolist(),
    "children_right": tree.children_right.tolist(),
    "features": tree.feature.tolist(),
    "thresholds": tree.threshold.tolist(),
    "values": tree.value[:, 0, :].tolist()
}

with open("phishing_tree.json", "w") as f:
    json.dump(tree_data, f, separators=(",", ":"))

size_bytes = os.path.getsize("phishing_tree.json")

print("Final tree depth:", final_model.get_depth())
print("Number of nodes:", final_model.tree_.node_count)
print("JSON model size:", round(size_bytes / 1024, 2), "KB")
print("Below 1 MB:", size_bytes < 1_000_000)

Final tree depth: 15
Number of nodes: 2395
JSON model size: 115.24 KB
Below 1 MB: True

In [ ]:

# STEP 13: Verify exported model structure and predictions

import json
import numpy as np

with open("phishing_tree.json", "r") as f:
    exported = json.load(f)

print("Feature count:", len(exported["feature_names"]))
print("Tree nodes:", len(exported["features"]))
print("Left-child count:", len(exported["children_left"]))
print("Right-child count:", len(exported["children_right"]))
print("Threshold count:", len(exported["thresholds"]))
print("Node values count:", len(exported["values"]))

# Check that all exported arrays have matching lengths
lengths = [
    len(exported["features"]),
    len(exported["children_left"]),
    len(exported["children_right"]),
    len(exported["thresholds"]),
    len(exported["values"])
]

print("\nStructure valid:", len(set(lengths)) == 1)

# Confirm the final model predicts both classes
sample_pred = final_model.predict(X_test.iloc[:10])
print("First 10 predictions:", sample_pred.tolist())
print("Prediction test completed.")

Feature count: 8
Tree nodes: 2395
Left-child count: 2395
Right-child count: 2395
Threshold count: 2395
Node values count: 2395

Structure valid: True
First 10 predictions: [0, 1, 0, 0, 0, 0, 0, 0, 1, 0]
Prediction test completed.

In [ ]:

# STEP 14: Test predictions from exported JSON

import json
import numpy as np

with open("phishing_tree.json", "r") as f:
    data = json.load(f)

def predict_json(row):
    node = 0

    while data["children_left"][node] != -1:
        feature = data["features"][node]
        threshold = data["thresholds"][node]

        if row[feature] <= threshold:
            node = data["children_left"][node]
        else:
            node = data["children_right"][node]

    return int(np.argmax(data["values"][node]))

# Test the first 100 URLs
X_sample = X_test.iloc[:100].to_numpy()

json_predictions = np.array([
    predict_json(row) for row in X_sample
])

python_predictions = final_model.predict(X_test.iloc[:100])

print("Predictions match:",
      np.array_equal(json_predictions, python_predictions))

print("Python model:", python_predictions[:10].tolist())
print("JSON model:  ", json_predictions[:10].tolist())

Predictions match: True
Python model: [0, 1, 0, 0, 0, 0, 0, 0, 1, 0]
JSON model:   [0, 1, 0, 0, 0, 0, 0, 0, 1, 0]

In [ ]:

from google.colab import files
files.download("phishing_tree.json")

In [ ]:
# TinyPhish: Final model prediction test

test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify",
    "192.168.1.1/login",
    "HTTPS://Example.com/path",
    "example.com/path",
    "https://[2001:db8::1]/login"
]

for url in test_urls:
    features = extract_features(url)

    sample = pd.DataFrame(
        [features], columns=feature_names
    )

    prediction = int(final_model.predict(sample)[0])
    label = "Phishing" if prediction == 1 else "Benign"

    print("URL:", url)
    print("Features:", features)
    print("Prediction:", prediction, "-", label)
    print()

URL: https://www.google.com
Features: [22, 2, 0, 1, 0, 0, 2, 0]
Prediction: 0 - Benign

URL: http://192.168.1.1/login@verify
Features: [31, 3, 0, 0, 1, 8, 3, 1]
Prediction: 1 - Phishing

URL: 192.168.1.1/login
Features: [17, 3, 0, 0, 0, 8, 1, 1]
Prediction: 1 - Phishing

URL: HTTPS://Example.com/path
Features: [24, 1, 0, 1, 0, 0, 3, 0]
Prediction: 1 - Phishing

URL: example.com/path
Features: [16, 1, 0, 0, 0, 0, 1, 0]
Prediction: 0 - Benign

URL: https://[2001:db8::1]/login
Features: [27, 0, 0, 1, 0, 6, 3, 1]
Prediction: 1 - Phishing

In [ ]:
# Compare Python and exported JSON predictions on the same URLs

test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify",
    "192.168.1.1/login",
    "HTTPS://Example.com/path",
    "example.com/path",
    "https://[2001:db8::1]/login"
]

for url in test_urls:
    features = extract_features(url)

    python_prediction = int(
        final_model.predict(
            pd.DataFrame([features], columns=feature_names)
        )[0]
    )

    json_prediction = predict_json(features)

    print("URL:", url)
    print("Python:", python_prediction)
    print("JSON:  ", json_prediction)
    print("Match:", python_prediction == json_prediction)
    print()

URL: https://www.google.com
Python: 0
JSON:   0
Match: True

URL: http://192.168.1.1/login@verify
Python: 1
JSON:   1
Match: True

URL: 192.168.1.1/login
Python: 1
JSON:   1
Match: True

URL: HTTPS://Example.com/path
Python: 1
JSON:   1
Match: True

URL: example.com/path
Python: 0
JSON:   0
Match: True

URL: https://[2001:db8::1]/login
Python: 1
JSON:   1
Match: True

In [ ]:
url = "http://192.168.1.1/login@verify"

features = extract_features(url)
sample = pd.DataFrame([features], columns=feature_names)

print("Original tree_model:", int(tree_model.predict(sample)[0]))
print("Final model:", int(final_model.predict(sample)[0]))
print("Exported JSON:", predict_json(features))

Original tree_model: 0
Final model: 1
Exported JSON: 1

In [ ]:
# TinyPhish: Final Model Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Predict using the final model
y_pred = final_model.predict(X_test)

# Calculate evaluation metrics
print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Precision:", round(precision_score(y_test, y_pred, zero_division=0), 4))
print("Recall:", round(recall_score(y_test, y_pred, zero_division=0), 4))
print("F1-score:", round(f1_score(y_test, y_pred, zero_division=0), 4))

# Confusion matrix: rows = actual, columns = predicted
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Detailed report
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Benign", "Phishing"],
    zero_division=0
))

Accuracy: 0.8983
Precision: 0.5957
Recall: 0.9138
F1-score: 0.7212

Confusion Matrix:
[[17671  2058]
 [  286  3032]]

Classification Report:
              precision    recall  f1-score   support

      Benign       0.98      0.90      0.94     19729
    Phishing       0.60      0.91      0.72      3318

    accuracy                           0.90     23047
   macro avg       0.79      0.90      0.83     23047
weighted avg       0.93      0.90      0.91     23047

In [ ]:
baseline_results = {
    "accuracy": 0.8983,
    "phishing_precision": 0.5957,
    "phishing_recall": 0.9138,
    "phishing_f1": 0.7212
}

print("TinyPhish baseline saved:")
for metric, score in baseline_results.items():
    print(f"{metric}: {score:.4f}")

TinyPhish baseline saved:
accuracy: 0.8983
phishing_precision: 0.5957
phishing_recall: 0.9138
phishing_f1: 0.7212

In [ ]:
# Check for URL overlap between training and test sets

train_urls = set(new_df.loc[X_train.index, "url"].astype(str))
test_urls = set(new_df.loc[X_test.index, "url"].astype(str))

overlap = train_urls.intersection(test_urls)

print("Unique training URLs:", len(train_urls))
print("Unique test URLs:", len(test_urls))
print("URLs appearing in both sets:", len(overlap))

Unique training URLs: 92184
Unique test URLs: 23047
URLs appearing in both sets: 0

In [ ]:
# Check duplicate URLs in the complete dataset

total_urls = len(new_df)
unique_urls = new_df["url"].astype(str).nunique()
duplicate_count = total_urls - unique_urls

print("Total dataset rows:", total_urls)
print("Unique URLs:", unique_urls)
print("Duplicate URL rows:", duplicate_count)
print(
    "Duplicate percentage:",
    round(duplicate_count / total_urls * 100, 2), "%"
)

Total dataset rows: 115231
Unique URLs: 115231
Duplicate URL rows: 0
Duplicate percentage: 0.0 %

In [ ]:
# Check class distribution in the complete dataset

print("Label distribution:")
print(new_df["label"].value_counts().sort_index())

print("\nClass percentages:")
print(
    (new_df["label"].value_counts(normalize=True)
     .sort_index() * 100).round(2)
)

print("\nMissing URLs:", new_df["url"].isna().sum())
print("Missing labels:", new_df["label"].isna().sum())
print("Unique labels:", sorted(new_df["label"].dropna().unique()))

Label distribution:
label
0    98641
1    16590
Name: count, dtype: int64

Class percentages:
label
0    85.6
1    14.4
Name: proportion, dtype: float64

Missing URLs: 0
Missing labels: 0
Unique labels: [np.int64(0), np.int64(1)]

In [ ]:
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix
)

y_pred = final_model.predict(X_test)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Phishing precision:", round(precision_score(y_test, y_pred), 4))
print("Phishing recall:", round(recall_score(y_test, y_pred), 4))
print("Phishing F1-score:", round(f1_score(y_test, y_pred), 4))

print("\nTrue negatives:", tn)
print("False positives:", fp)
print("False negatives:", fn)
print("True positives:", tp)

Accuracy: 0.8983
Phishing precision: 0.5957
Phishing recall: 0.9138
Phishing F1-score: 0.7212

True negatives: 17671
False positives: 2058
False negatives: 286
True positives: 3032

In [ ]:
# Split training data into training and validation sets

from sklearn.model_selection import train_test_split

X_train_new, X_val, y_train_new, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.2,
    random_state=42,
    stratify=y_train
)

print("New training samples:", len(X_train_new))
print("Validation samples:", len(X_val))
print("Test samples (untouched):", len(X_test))

New training samples: 73747
Validation samples: 18437
Test samples (untouched): 23047

In [ ]:
# Compare decision-tree settings on validation data

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score
)

settings = [
    {"max_depth": 8,  "min_samples_leaf": 5},
    {"max_depth": 10, "min_samples_leaf": 5},
    {"max_depth": 12, "min_samples_leaf": 5}
]

for setting in settings:
    model = DecisionTreeClassifier(
        max_depth=setting["max_depth"],
        min_samples_leaf=setting["min_samples_leaf"],
        class_weight="balanced",
        random_state=42
    )

    model.fit(X_train_new, y_train_new)
    pred = model.predict(X_val)

    print("\nSettings:", setting)
    print("Accuracy:", round(accuracy_score(y_val, pred), 4))
    print("Precision:", round(precision_score(y_val, pred, zero_division=0), 4))
    print("Recall:", round(recall_score(y_val, pred, zero_division=0), 4))
    print("F1-score:", round(f1_score(y_val, pred, zero_division=0), 4))
    print("Tree depth:", model.get_depth())
    print("Number of nodes:", model.tree_.node_count)

Settings: {'max_depth': 8, 'min_samples_leaf': 5}
Accuracy: 0.8869
Precision: 0.5653
Recall: 0.9277
F1-score: 0.7025
Tree depth: 8
Number of nodes: 343

Settings: {'max_depth': 10, 'min_samples_leaf': 5}
Accuracy: 0.888
Precision: 0.5676
Recall: 0.9318
F1-score: 0.7055
Tree depth: 10
Number of nodes: 799

Settings: {'max_depth': 12, 'min_samples_leaf': 5}
Accuracy: 0.8969
Precision: 0.5907
Recall: 0.9239
F1-score: 0.7206
Tree depth: 12
Number of nodes: 1415

In [ ]:
import os
import pandas as pd

file_path = "phishing_features.csv"

if os.path.exists(file_path):
    backup_df = pd.read_csv(file_path)

    print("Shape:", backup_df.shape)
    print("\nColumns:")
    print(backup_df.columns.tolist())

    print("\nFirst 5 rows:")
    print(backup_df.head())

    print("\nMissing values:")
    print(backup_df.isna().sum())

    print("\nLabel distribution:")
    print(backup_df["label"].value_counts(dropna=False))
else:
    print("phishing_features.csv is not in the current Colab directory.")

Shape: (160064, 13)

Columns:
['url', 'label', 'url_length', 'num_dots', 'has_https', 'has_ip', 'num_subdirs', 'num_params', 'suspicious_words', 'tld', 'special_char_count', 'digits_count', 'entropy']

First 5 rows:
                                                 url  label  url_length  \
0  http://forum.uk.securebankinggroup.com/107519/...      1          89
1                          http://b45042.com/fish/29      1          25
2                     http://bet73018.com/lottery/99      1          30
3            https://logiin--metsa-autho.webflow.io/      1          39
4              https://mettamasklogiiann.webflow.io/      1          37

   num_dots  has_https  has_ip  num_subdirs  num_params  suspicious_words  \
0         3          0       0            5           0                 2
1         1          0       0            4           0                 0
2         1          0       0            4           0                 0
3         2          1       0            3           0                 0
4         2          1       0            3           0                 0

   tld  special_char_count  digits_count   entropy
0  com                   4            29  4.792985
1  com                   0             7  4.003856
2  com                   0             7  4.053236
3   io                   3             0  4.150411
4   io                   0             0  4.100817

Missing values:
url                     0
label                   0
url_length              0
num_dots                0
has_https               0
has_ip                  0
num_subdirs             0
num_params              0
suspicious_words        0
tld                   821
special_char_count      0
digits_count            0
entropy                 0
dtype: int64

Label distribution:
label
1    159244
0       820
Name: count, dtype: int64

In [ ]:
import os
import pandas as pd

file_path = "phishing_features.csv"

if os.path.exists(file_path):
    backup_df = pd.read_csv(file_path)

    print("Shape:", backup_df.shape)
    print("\nColumns:")
    print(backup_df.columns.tolist())

    print("\nFirst 5 rows:")
    print(backup_df.head())

    print("\nMissing values:")
    print(backup_df.isna().sum())

    print("\nLabel distribution:")
    print(backup_df["label"].value_counts(dropna=False))
else:
    print("phishing_features.csv is not in the current Colab directory.")

Shape: (160064, 13)

Columns:
['url', 'label', 'url_length', 'num_dots', 'has_https', 'has_ip', 'num_subdirs', 'num_params', 'suspicious_words', 'tld', 'special_char_count', 'digits_count', 'entropy']

First 5 rows:
                                                 url  label  url_length  \
0  http://forum.uk.securebankinggroup.com/107519/...      1          89
1                          http://b45042.com/fish/29      1          25
2                     http://bet73018.com/lottery/99      1          30
3            https://logiin--metsa-autho.webflow.io/      1          39
4              https://mettamasklogiiann.webflow.io/      1          37

   num_dots  has_https  has_ip  num_subdirs  num_params  suspicious_words  \
0         3          0       0            5           0                 2
1         1          0       0            4           0                 0
2         1          0       0            4           0                 0
3         2          1       0            3           0                 0
4         2          1       0            3           0                 0

   tld  special_char_count  digits_count   entropy
0  com                   4            29  4.792985
1  com                   0             7  4.003856
2  com                   0             7  4.053236
3   io                   3             0  4.150411
4   io                   0             0  4.100817

Missing values:
url                     0
label                   0
url_length              0
num_dots                0
has_https               0
has_ip                  0
num_subdirs             0
num_params              0
suspicious_words        0
tld                   821
special_char_count      0
digits_count            0
entropy                 0
dtype: int64

Label distribution:
label
1    159244
0       820
Name: count, dtype: int64

In [ ]:
# Check URL overlap between current and backup datasets

current_urls = set(new_df["url"].astype(str).str.strip().str.lower())
backup_urls = set(backup_df["url"].astype(str).str.strip().str.lower())

overlap = current_urls.intersection(backup_urls)

print("Unique current URLs:", len(current_urls))
print("Unique backup URLs:", len(backup_urls))
print("URLs present in both datasets:", len(overlap))

Unique current URLs: 115227
Unique backup URLs: 160064
URLs present in both datasets: 9018

In [ ]:
# Check labels of URLs shared by both datasets

current_check = new_df[["url", "label"]].copy()
backup_check = backup_df[["url", "label"]].copy()

current_check["url_key"] = (
    current_check["url"].astype(str).str.strip().str.lower()
)
backup_check["url_key"] = (
    backup_check["url"].astype(str).str.strip().str.lower()
)

# Keep one row per URL before comparing
current_check = current_check.drop_duplicates("url_key")
backup_check = backup_check.drop_duplicates("url_key")

shared = current_check[["url_key", "label"]].merge(
    backup_check[["url_key", "label"]],
    on="url_key",
    suffixes=("_current", "_backup")
)

print("Shared URLs checked:", len(shared))
print(
    "Same labels:",
    (shared["label_current"] == shared["label_backup"]).sum()
)
print(
    "Conflicting labels:",
    (shared["label_current"] != shared["label_backup"]).sum()
)

print("\nLabel comparison:")
print(pd.crosstab(
    shared["label_current"],
    shared["label_backup"],
    rownames=["Current dataset"],
    colnames=["Backup dataset"]
))

Shared URLs checked: 9018
Same labels: 9018
Conflicting labels: 0

Label comparison:
Backup dataset      1
Current dataset
1                9018

In [ ]:
# Find URLs that exist only in the backup dataset

current_urls = set(
    new_df["url"].astype(str).str.strip().str.lower()
)

backup_df["url_key"] = (
    backup_df["url"].astype(str).str.strip().str.lower()
)

backup_unique = backup_df[
    ~backup_df["url_key"].isin(current_urls)
].copy()

print("Total backup rows:", len(backup_df))
print("Backup URLs not in current dataset:", len(backup_unique))

print("\nLabels of additional URLs:")
print(backup_unique["label"].value_counts())

print("\nSample additional URLs:")
print(backup_unique[["url", "label"]].head(10).to_string(index=False))

Total backup rows: 160064
Backup URLs not in current dataset: 151046

Labels of additional URLs:
label
1    150226
0       820
Name: count, dtype: int64

Sample additional URLs:
                                                                                      url  label
http://forum.uk.securebankinggroup.com/107519/8af662/475d964a-0243-46bf-aefd-66da26254efa      1
                                                                http://b45042.com/fish/29      1
                                                           http://bet73018.com/lottery/99      1
                                                  https://logiin--metsa-autho.webflow.io/      1
                                                    https://mettamasklogiiann.webflow.io/      1
                                                          http://bet73018.com/lottery/134      1
                                                     https://metamasklogenies.webflow.io/      1
                                                     https://mmettamaskilogin.webflow.io/      1
                                     https://www.robiox.com.py/users/322503287968/profile      1
                                                    https://xbancobhd2025xxxxxxxxx.xo.je/      1

In [ ]:
from urllib.parse import urlparse

def get_hostname(url):
    url = str(url).strip()
    if "://" not in url:
        url = "http://" + url

    try:
        return (urlparse(url).hostname or "").lower().removeprefix("www.")
    except ValueError:
        return ""

# Extract hostnames from both datasets
current_hosts = set(new_df["url"].apply(get_hostname))
backup_unique["hostname"] = backup_unique["url"].apply(get_hostname)

backup_hosts = set(backup_unique["hostname"]) - {""}
shared_hosts = current_hosts.intersection(backup_hosts)

print("Unique current hostnames:", len(current_hosts - {""}))
print("Unique additional backup hostnames:", len(backup_hosts))
print("Additional backup hostnames also in current dataset:", len(shared_hosts))

print("\nSample shared hostnames:")
print(list(sorted(shared_hosts))[:10])

Unique current hostnames: 102745
Unique additional backup hostnames: 52913
Additional backup hostnames also in current dataset: 323

Sample shared hostnames:
['1drv.ms', '2f6crk.share-eu1.hsforms.com', '5mp.eu', 'about.me', 'absf4csecurity.co.za', 'academy-skrf.ru', 'acer.com', 'acm.org', 'acoustic-apartment-low.on-fleek.app', 'adobe.com']

In [ ]:
# Check whether any hostname has both labels in the backup dataset

backup_check = backup_df.copy()
backup_check["hostname"] = backup_check["url"].apply(get_hostname)

hostname_label_counts = backup_check.groupby("hostname")["label"].nunique()

conflicting_hosts = hostname_label_counts[hostname_label_counts > 1]

print("Hostnames checked:", backup_check["hostname"].nunique())
print("Hostnames with both labels:", len(conflicting_hosts))

if len(conflicting_hosts) > 0:
    print("\nSample hostnames with conflicting labels:")
    print(conflicting_hosts.head(10))

Hostnames checked: 57203
Hostnames with both labels: 17

Sample hostnames with conflicting labels:
hostname
airtable.com        2
archive.org         2
bing.com            2
bitbucket.org       2
drive.google.com    2
dropbox.com         2
evernote.com        2
github.com          2
gitlab.com          2
google.com          2
Name: label, dtype: int64

In [ ]:
counts = backup_unique["label"].value_counts()

print("Additional URLs:", len(backup_unique))
print("\nLabel percentages:")
print((backup_unique["label"].value_counts(normalize=True) * 100).round(2))

print("\nBenign URLs:", counts.get(0, 0))
print("Phishing URLs:", counts.get(1, 0))

Additional URLs: 151046

Label percentages:
label
1    99.46
0     0.54
Name: proportion, dtype: float64

Benign URLs: 820
Phishing URLs: 150226

In [ ]:
# Create a balanced sample from additional backup URLs

backup_phishing = backup_unique[backup_unique["label"] == 1]
backup_benign = backup_unique[backup_unique["label"] == 0]

backup_sample = pd.concat([
    backup_phishing.sample(
        n=min(820, len(backup_phishing)), random_state=42
    ),
    backup_benign.sample(
        n=min(820, len(backup_benign)), random_state=42
    )
])

print("Balanced backup sample:", len(backup_sample))
print("\nLabel counts:")
print(backup_sample["label"].value_counts())

Balanced backup sample: 1640

Label counts:
label
1    820
0    820
Name: count, dtype: int64

In [ ]:
# Extract the same features used by TinyPhish

backup_sample_X = pd.DataFrame(
    backup_sample["url"].apply(extract_features).tolist(),
    columns=feature_names,
    index=backup_sample.index
)

backup_sample_y = backup_sample["label"].astype(int)

print("Feature shape:", backup_sample_X.shape)
print("Label shape:", backup_sample_y.shape)
print("\nFeature columns:")
print(backup_sample_X.columns.tolist())

print("\nMissing feature values:", backup_sample_X.isnull().sum().sum())

Feature shape: (1640, 8)
Label shape: (1640,)

Feature columns:
['url_length', 'num_dots', 'num_hyphens', 'has_https', 'has_at', 'num_digits', 'num_slashes', 'has_ip']

Missing feature values: 0

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

# Model A: Current dataset only
model_a = DecisionTreeClassifier(
    max_depth=15,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42
)

model_a.fit(X_train_new, y_train_new)
pred_a = model_a.predict(X_val)

# Model B: Current data + balanced backup sample
X_train_b = pd.concat([X_train_new, backup_sample_X], ignore_index=True)
y_train_b = pd.concat([y_train_new.reset_index(drop=True),
                       backup_sample_y.reset_index(drop=True)])

model_b = DecisionTreeClassifier(
    max_depth=15,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42
)

model_b.fit(X_train_b, y_train_b)
pred_b = model_b.predict(X_val)

# Compare validation results
results = pd.DataFrame({
    "Metric": ["Accuracy", "Phishing Precision", "Phishing Recall", "Phishing F1"],
    "Model A": [
        accuracy_score(y_val, pred_a),
        precision_score(y_val, pred_a, zero_division=0),
        recall_score(y_val, pred_a, zero_division=0),
        f1_score(y_val, pred_a, zero_division=0)
    ],
    "Model B": [
        accuracy_score(y_val, pred_b),
        precision_score(y_val, pred_b, zero_division=0),
        recall_score(y_val, pred_b, zero_division=0),
        f1_score(y_val, pred_b, zero_division=0)
    ]
})

print(results.round(4).to_string(index=False))
print("\nModel A tree nodes:", model_a.tree_.node_count)
print("Model B tree nodes:", model_b.tree_.node_count)

            Metric  Model A  Model B
          Accuracy   0.8957   0.8956
Phishing Precision   0.5880   0.5880
   Phishing Recall   0.9205   0.9179
       Phishing F1   0.7176   0.7168

Model A tree nodes: 2079
Model B tree nodes: 2259

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

for depth in [8, 10, 12]:
    model = DecisionTreeClassifier(
        max_depth=depth,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=42
    )

    model.fit(X_train_new, y_train_new)
    pred = model.predict(X_val)

    print(f"\nMax depth: {depth}")
    print("Accuracy:", round(accuracy_score(y_val, pred), 4))
    print("Phishing precision:", round(precision_score(y_val, pred, zero_division=0), 4))
    print("Phishing recall:", round(recall_score(y_val, pred, zero_division=0), 4))
    print("Phishing F1:", round(f1_score(y_val, pred, zero_division=0), 4))
    print("Tree nodes:", model.tree_.node_count)

Max depth: 8
Accuracy: 0.8869
Phishing precision: 0.5653
Phishing recall: 0.9277
Phishing F1: 0.7025
Tree nodes: 343

Max depth: 10
Accuracy: 0.888
Phishing precision: 0.5676
Phishing recall: 0.9318
Phishing F1: 0.7055
Tree nodes: 799

Max depth: 12
Accuracy: 0.8969
Phishing precision: 0.5907
Phishing recall: 0.9239
Phishing F1: 0.7206
Tree nodes: 1415

In [ ]:
import json
import os
from sklearn.tree import DecisionTreeClassifier

candidate_model = DecisionTreeClassifier(
    max_depth=12,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42
)

candidate_model.fit(X_train, y_train)

tree = candidate_model.tree_

tree_data = {
    "feature_names": feature_names,
    "children_left": tree.children_left.tolist(),
    "children_right": tree.children_right.tolist(),
    "features": tree.feature.tolist(),
    "thresholds": tree.threshold.tolist(),
    "values": tree.value[:, 0, :].tolist()
}

with open("phishing_tree_depth12.json", "w") as f:
    json.dump(tree_data, f, separators=(",", ":"))

size_bytes = os.path.getsize("phishing_tree_depth12.json")

print("Tree nodes:", tree.node_count)
print("JSON size:", size_bytes, "bytes")
print("JSON size:", round(size_bytes / 1024, 2), "KB")

Tree nodes: 1523
JSON size: 75427 bytes
JSON size: 73.66 KB

In [ ]:
import json
import numpy as np

with open("phishing_tree_depth12.json", "r") as f:
    tree_data = json.load(f)

def predict_from_json(row, tree):
    node = 0

    while tree["children_left"][node] != -1:
        feature = tree["features"][node]
        threshold = tree["thresholds"][node]

        if row[feature] <= threshold:
            node = tree["children_left"][node]
        else:
            node = tree["children_right"][node]

    return int(np.argmax(tree["values"][node]))

sample = X_test.iloc[:100].to_numpy()

python_predictions = candidate_model.predict(sample)
json_predictions = [
    predict_from_json(row, tree_data) for row in sample
]

print("Predictions match:",
      np.array_equal(python_predictions, json_predictions))

Predictions match: True

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

y_pred = candidate_model.predict(X_test)

print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Phishing precision:", round(precision_score(y_test, y_pred, zero_division=0), 4))
print("Phishing recall:", round(recall_score(y_test, y_pred, zero_division=0), 4))
print("Phishing F1:", round(f1_score(y_test, y_pred, zero_division=0), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(
    y_test, y_pred,
    target_names=["Benign", "Phishing"],
    zero_division=0
))

Accuracy: 0.8962
Phishing precision: 0.5895
Phishing recall: 0.9195
Phishing F1: 0.7184

Confusion Matrix:
[[17604  2125]
 [  267  3051]]

Classification Report:
              precision    recall  f1-score   support

      Benign       0.99      0.89      0.94     19729
    Phishing       0.59      0.92      0.72      3318

    accuracy                           0.90     23047
   macro avg       0.79      0.91      0.83     23047
weighted avg       0.93      0.90      0.90     23047

In [ ]:
custom_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify",
    "192.168.1.1/login",
    "HTTPS://Example.com/path",
    "example.com/path",
    "https://[2001:db8::1]/login"
]

custom_X = pd.DataFrame(
    [extract_features(url) for url in custom_urls],
    columns=feature_names
)

old_predictions = final_model.predict(custom_X)
new_predictions = candidate_model.predict(custom_X)

for url, old, new in zip(
    custom_urls, old_predictions, new_predictions
):
    print(f"URL: {url}")
    print(f"Old model: {int(old)} | New depth-12 model: {int(new)}")
    print()

URL: https://www.google.com
Old model: 0 | New depth-12 model: 0

URL: http://192.168.1.1/login@verify
Old model: 1 | New depth-12 model: 1

URL: 192.168.1.1/login
Old model: 1 | New depth-12 model: 1

URL: HTTPS://Example.com/path
Old model: 1 | New depth-12 model: 1

URL: example.com/path
Old model: 0 | New depth-12 model: 0

URL: https://[2001:db8::1]/login
Old model: 1 | New depth-12 model: 1

In [ ]:
from google.colab import files
files.download("phishing_tree_depth12.json")

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score, recall_score, f1_score

for leaf_size in [10, 20, 50]:
    model = DecisionTreeClassifier(
        max_depth=15,
        min_samples_leaf=leaf_size,
        class_weight="balanced",
        random_state=42
    )

    model.fit(X_train_new, y_train_new)
    pred = model.predict(X_val)

    print("\nMin samples per leaf:", leaf_size)
    print("Precision:", round(
        precision_score(y_val, pred, zero_division=0), 4))
    print("Recall:", round(
        recall_score(y_val, pred, zero_division=0), 4))
    print("F1-score:", round(
        f1_score(y_val, pred, zero_division=0), 4))
    print("Nodes:", model.tree_.node_count)

Min samples per leaf: 10
Precision: 0.5865
Recall: 0.9231
F1-score: 0.7173
Nodes: 1643

Min samples per leaf: 20
Precision: 0.5862
Recall: 0.9224
F1-score: 0.7168
Nodes: 1275

Min samples per leaf: 50
Precision: 0.5656
Recall: 0.9258
F1-score: 0.7022
Nodes: 817

In [ ]:
print("Backup dataset shape:", backup_df.shape)

print("\nColumns:")
print(backup_df.columns.tolist())

print("\nMissing values:")
print(backup_df.isnull().sum())

print("\nLabel counts:")
print(backup_df["label"].value_counts())

print("\nLabel percentages:")
print(
    (backup_df["label"].value_counts(normalize=True) * 100)
    .round(2)
)

Backup dataset shape: (160064, 14)

Columns:
['url', 'label', 'url_length', 'num_dots', 'has_https', 'has_ip', 'num_subdirs', 'num_params', 'suspicious_words', 'tld', 'special_char_count', 'digits_count', 'entropy', 'url_key']

Missing values:
url                     0
label                   0
url_length              0
num_dots                0
has_https               0
has_ip                  0
num_subdirs             0
num_params              0
suspicious_words        0
tld                   821
special_char_count      0
digits_count            0
entropy                 0
url_key                 0
dtype: int64

Label counts:
label
1    159244
0       820
Name: count, dtype: int64

Label percentages:
label
1    99.49
0     0.51
Name: proportion, dtype: float64

In [ ]:
# Check duplicate URLs and label consistency

print("Backup duplicate url_key values:",
      backup_df["url_key"].duplicated().sum())

print("Main dataset duplicate URLs:",
      new_df["url"].str.strip().str.lower().duplicated().sum())

main_check = new_df[["url", "label"]].copy()
main_check["url_key"] = main_check["url"].str.strip().str.lower()

backup_check = backup_df[["url_key", "label"]].copy()

overlap = main_check.merge(
    backup_check,
    on="url_key",
    how="inner",
    suffixes=("_main", "_backup")
)

print("\nOverlapping rows:", len(overlap))
print("Same label:",
      (overlap["label_main"] == overlap["label_backup"]).sum())
print("Conflicting label:",
      (overlap["label_main"] != overlap["label_backup"]).sum())

Backup duplicate url_key values: 0
Main dataset duplicate URLs: 4

Overlapping rows: 9018
Same label: 9018
Conflicting label: 0

In [ ]:
print("Main dataset columns:")
print(new_df.columns.tolist())

print("\nMain dataset sample:")
print(new_df.head(3).to_string())

print("\nBackup dataset columns:")
print(backup_df.columns.tolist())

Main dataset columns:
['url', 'url_len', 'dom', 'dom_len', 'is_ip', 'tld', 'tld_len', 'subdom_cnt', 'letter_cnt', 'digit_cnt', 'special_cnt', 'eq_cnt', 'qm_cnt', 'amp_cnt', 'dot_cnt', 'dash_cnt', 'under_cnt', 'letter_ratio', 'digit_ratio', 'spec_ratio', 'is_https', 'slash_cnt', 'entropy', 'path_len', 'query_len', 'label']

Main dataset sample:
                          url  url_len             dom  dom_len  is_ip     tld  tld_len  subdom_cnt  letter_cnt  digit_cnt  special_cnt  eq_cnt  qm_cnt  amp_cnt  dot_cnt  dash_cnt  under_cnt  letter_ratio  digit_ratio  spec_ratio  is_https  slash_cnt   entropy  path_len  query_len  label
0    https://www.rmit.edu.au/       24     rmit.edu.au       11      0  edu.au        6           1          17          0            7       0       0        0        3         0          0      0.708333          0.0    0.291667         1          3  3.709148         1          0      0
1  http://www.latrobe.edu.au/       26  latrobe.edu.au       14      0  edu.au        6           1          19          0            7       0       0        0        3         0          0      0.730769          0.0    0.269231         0          3  3.738149         1          0      0
2     https://www.cqu.edu.au/       23      cqu.edu.au       10      0  edu.au        6           1          16          0            7       0       0        0        3         0          0      0.695652          0.0    0.304348         1          3  3.609668         1          0      0

Backup dataset columns:
['url', 'label', 'url_length', 'num_dots', 'has_https', 'has_ip', 'num_subdirs', 'num_params', 'suspicious_words', 'tld', 'special_char_count', 'digits_count', 'entropy', 'url_key']

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    confusion_matrix
)

weights = [
    {0: 1, 1: 2},
    {0: 1, 1: 3},
    {0: 1, 1: 4}
]

for weight in weights:
    model = DecisionTreeClassifier(
        max_depth=12,
        min_samples_leaf=5,
        class_weight=weight,
        random_state=42
    )

    model.fit(X_train_new, y_train_new)
    pred = model.predict(X_val)

    tn, fp, fn, tp = confusion_matrix(
        y_val, pred, labels=[0, 1]
    ).ravel()

    print("\nClass weights:", weight)
    print("Phishing precision:",
          round(precision_score(y_val, pred, zero_division=0), 4))
    print("Phishing recall:",
          round(recall_score(y_val, pred, zero_division=0), 4))
    print("Phishing F1:",
          round(f1_score(y_val, pred, zero_division=0), 4))
    print("False positives:", fp)
    print("False negatives:", fn)
    print("Tree nodes:", model.tree_.node_count)

Class weights: {0: 1, 1: 2}
Phishing precision: 0.762
Phishing recall: 0.7928
Phishing F1: 0.7771
False positives: 657
False negatives: 550
Tree nodes: 1491

Class weights: {0: 1, 1: 3}
Phishing precision: 0.6982
Phishing recall: 0.8482
Phishing F1: 0.7659
False positives: 973
False negatives: 403
Tree nodes: 1397

Class weights: {0: 1, 1: 4}
Phishing precision: 0.643
Phishing recall: 0.8953
Phishing F1: 0.7485
False positives: 1319
False negatives: 278
Tree nodes: 1409

In [ ]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_score, recall_score, f1_score

model = DecisionTreeClassifier(
    max_depth=12,
    min_samples_leaf=5,
    class_weight={0: 1, 1: 2},
    random_state=42
)

model.fit(X_train_new, y_train_new)

phishing_probability = model.predict_proba(X_val)[:, 1]

for threshold in [0.30, 0.40, 0.50, 0.60]:
    pred = (phishing_probability >= threshold).astype(int)

    print(f"\nThreshold: {threshold}")
    print("Precision:", round(
        precision_score(y_val, pred, zero_division=0), 4))
    print("Recall:", round(
        recall_score(y_val, pred, zero_division=0), 4))
    print("F1-score:", round(
        f1_score(y_val, pred, zero_division=0), 4))

Threshold: 0.3
Precision: 0.6146
Recall: 0.9084
F1-score: 0.7332

Threshold: 0.4
Precision: 0.69
Recall: 0.8564
F1-score: 0.7643

Threshold: 0.5
Precision: 0.7568
Recall: 0.7973
F1-score: 0.7765

Threshold: 0.6
Precision: 0.8347
Recall: 0.7494
F1-score: 0.7898

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix
)

model = DecisionTreeClassifier(
    max_depth=12,
    min_samples_leaf=5,
    class_weight={0: 1, 1: 2},
    random_state=42
)

# Train on the full training set
model.fit(X_train, y_train)

# Apply the selected threshold
probability = model.predict_proba(X_test)[:, 1]
pred = (probability >= 0.30).astype(int)

print("Accuracy:", round(accuracy_score(y_test, pred), 4))
print("Precision:", round(precision_score(y_test, pred), 4))
print("Recall:", round(recall_score(y_test, pred), 4))
print("F1-score:", round(f1_score(y_test, pred), 4))
print("Confusion Matrix:")
print(confusion_matrix(y_test, pred))

Accuracy: 0.9087
Precision: 0.6278
Recall: 0.8987
F1-score: 0.7392
Confusion Matrix:
[[17961  1768]
 [  336  2982]]

In [ ]:

import json

tree = model.tree_

model_json = {
    "children_left": tree.children_left.tolist(),
    "children_right": tree.children_right.tolist(),
    "feature": tree.feature.tolist(),
    "threshold": tree.threshold.tolist(),
    "value": tree.value.tolist()
}

json_text = json.dumps(model_json)
size_kb = len(json_text.encode("utf-8")) / 1024

print("Tree nodes:", tree.node_count)
print("Estimated JSON size:", round(size_kb, 2), "KB")
print("Under 1 MB:", size_kb < 1024)

Tree nodes: 1477
Estimated JSON size: 80.47 KB
Under 1 MB: True

In [ ]:

import json
import numpy as np

tree = model.tree_

model_data = {
    "children_left": tree.children_left.tolist(),
    "children_right": tree.children_right.tolist(),
    "feature": tree.feature.tolist(),
    "threshold": tree.threshold.tolist(),
    "value": tree.value.tolist(),
    "classes": model.classes_.tolist()
}

with open("phishing_tree_threshold03.json", "w") as f:
    json.dump(model_data, f)

import os
print("Actual file size:",
      round(os.path.getsize("phishing_tree_threshold03.json") / 1024, 2),
      "KB")

Actual file size: 80.49 KB

In [ ]:

import json
import os

tree = model.tree_

model_data = {
    "children_left": tree.children_left.tolist(),
    "children_right": tree.children_right.tolist(),
    "features": tree.feature.tolist(),
    "thresholds": tree.threshold.tolist(),
    "values": tree.value.squeeze(axis=1).tolist()
}

with open("phishing_tree_threshold03_android.json", "w") as f:
    json.dump(model_data, f)

print("File size:",
      round(os.path.getsize("phishing_tree_threshold03_android.json") / 1024, 2),
      "KB")
print("JSON keys:", list(model_data.keys()))

File size: 77.59 KB
JSON keys: ['children_left', 'children_right', 'features', 'thresholds', 'values']

In [ ]:
from google.colab import files

files.download("phishing_tree_threshold03_android.json")

In [ ]:

url = "192.168.1.1/login"

features = extract_features(url)
probability = model.predict_proba([features])[0][1]
prediction = 1 if probability >= 0.30 else 0

print("URL:", url)
print("Phishing probability:", round(probability, 4))
print("Python prediction:",
      "Phishing" if prediction == 1 else "Benign")

URL: 192.168.1.1/login
Phishing probability: 0.2857
Python prediction: Benign

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:

import pandas as pd

url = "HTTPS://Example.com/path"

features = extract_features(url)
X_one = pd.DataFrame([features], columns=feature_names)

probability = model.predict_proba(X_one)[0][1]
prediction = 1 if probability >= 0.30 else 0

print("URL:", url)
print("Phishing probability:", round(probability, 4))
print("Python prediction:",
      "Phishing" if prediction == 1 else "Benign")

URL: HTTPS://Example.com/path
Phishing probability: 0.255
Python prediction: Benign

In [ ]:

import pandas as pd

url = "example.com/path"

features = extract_features(url)
X_one = pd.DataFrame([features], columns=feature_names)

probability = model.predict_proba(X_one)[0][1]
prediction = 1 if probability >= 0.30 else 0

print("URL:", url)
print("Phishing probability:", round(probability, 4))
print("Python prediction:",
      "Phishing" if prediction == 1 else "Benign")

URL: example.com/path
Phishing probability: 0.0
Python prediction: Benign

In [ ]:

import pandas as pd

url = "https://[2001:db8::1]/login"

features = extract_features(url)
X_one = pd.DataFrame([features], columns=feature_names)

probability = model.predict_proba(X_one)[0][1]
prediction = 1 if probability >= 0.30 else 0

print("URL:", url)
print("Phishing probability:", round(probability, 4))
print("Python prediction:",
      "Phishing" if prediction == 1 else "Benign")

URL: https://[2001:db8::1]/login
Phishing probability: 0.9865
Python prediction: Phishing

In [ ]:

import pandas as pd

test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify"
]

for url in test_urls:
    features = extract_features(url)
    X_one = pd.DataFrame([features], columns=feature_names)

    probability = model.predict_proba(X_one)[0][1]
    prediction = 1 if probability >= 0.30 else 0

    print("\nURL:", url)
    print("Phishing probability:", round(probability, 4))
    print("Python prediction:",
          "Phishing" if prediction == 1 else "Benign")

URL: https://www.google.com
Phishing probability: 0.0
Python prediction: Benign

URL: http://192.168.1.1/login@verify
Phishing probability: 0.4444
Python prediction: Phishing

In [ ]:

import pandas as pd
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))

phishbd_df = pd.read_csv(filename)

print("Dataset filename:", filename)
print("Dataset shape:", phishbd_df.shape)

print("\nColumn names:")
print(phishbd_df.columns.tolist())

print("\nFirst 5 rows:")
display(phishbd_df.head())

Saving PhishBD_2026_73_features.csv to PhishBD_2026_73_features.csv
Dataset filename: PhishBD_2026_73_features.csv
Dataset shape: (131167, 75)

Column names:
['url', 'label', 'url_length', 'domain_length', 'subdomain_length', 'path_length', 'query_length', 'dot_count', 'hyphen_count', 'underscore_count', 'slash_count', 'at_count', 'eq_count', 'amp_count', 'percent_count', 'digit_count', 'letter_count', 'special_char_count', 'subdomain_count', 'path_depth', 'query_param_count', 'tld_length', 'digit_ratio', 'letter_ratio', 'entropy_url', 'entropy_domain', 'entropy_subdomain', 'cv_ratio_url', 'cv_ratio_domain', 'longest_consonant_run', 'token_count', 'avg_token_length', 'max_token_length', 'numeric_token_count', 'min_brand_edit_distance', 'digit_substitution_score', 'tld_count_in_url', 'consec_digits_domain', 'new_path_token_entropy', 'new_domain_vowel_ratio', 'new_query_key_count', 'new_susp_word_count', 'new_url_digit_letter_ratio', 'has_ip', 'is_https', 'has_at', 'has_double_slash', 'has_port', 'is_shortened', 'has_http_in_domain', 'has_suspicious_words', 'domain_has_digit', 'domain_has_hyphen', 'has_fragment', 'has_repeated_tokens', 'bd_brand_in_url', 'bd_brand_in_sub_not_domain', 'bd_brand_in_path_not_domain', 'bd_gov_keyword', 'is_free_tld', 'is_bd_tld', 'bd_brand_free_tld', 'is_typosquatting', 'has_repeated_chars', 'has_punycode', 'has_redirect_param', 'has_base64', 'multiple_tlds', 'has_hex_encoding', 'has_login_path', 'new_tld_is_bd', 'new_brand_in_query', 'new_has_encoded_chars', 'new_path_has_exe', 'new_subdomain_is_ip_like']

First 5 rows:

,url,label,url_length,domain_length,subdomain_length,path_length,query_length,dot_count,hyphen_count,underscore_count,...,has_redirect_param,has_base64,multiple_tlds,has_hex_encoding,has_login_path,new_tld_is_bd,new_brand_in_query,new_has_encoded_chars,new_path_has_exe,new_subdomain_is_ip_like
0,http://www.au-payccoy.aseacaameoy.tvxp.top/AU/...,1,55.0,4.0,26.0,13.0,0.0,5.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,http://hkpgk.the-drone-company.com,1,34.0,17.0,5.0,0.0,0.0,2.0,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,http://marconishop.com,1,22.0,11.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,http://stage-coingeb.com,1,24.0,13.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,http://xgiqfrqcebklsdsyy.click,1,30.0,17.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:

# STEP 2: Inspect labels and Bangladesh-specific features

print("1. LABEL COUNTS")
print(phishbd_df["label"].value_counts(dropna=False))

print("\n2. MISSING VALUES")
print("Rows with missing labels:", phishbd_df["label"].isna().sum())
print("Rows with missing URLs:", phishbd_df["url"].isna().sum())

print("\n3. DUPLICATE URL COUNT")
print("Duplicate URLs:", phishbd_df["url"].duplicated().sum())

# Bangladesh and lookalike-related features
brand_features = [
    "bd_brand_in_url",
    "bd_brand_in_sub_not_domain",
    "bd_brand_in_path_not_domain",
    "min_brand_edit_distance",
    "digit_substitution_score",
    "is_typosquatting",
    "new_brand_in_query"
]

print("\n4. BRAND FEATURE SUMMARY")
display(phishbd_df[brand_features].describe().T)

print("\n5. URL COUNTS WITH BRAND FLAGS")
for feature in [
    "bd_brand_in_url",
    "bd_brand_in_sub_not_domain",
    "bd_brand_in_path_not_domain",
    "is_typosquatting",
    "new_brand_in_query"
]:
    print(f"{feature}:",
          (phishbd_df[feature] == 1).sum())

1. LABEL COUNTS
label
1    91817
0    39350
Name: count, dtype: int64

2. MISSING VALUES
Rows with missing labels: 0
Rows with missing URLs: 0

3. DUPLICATE URL COUNT
Duplicate URLs: 0

4. BRAND FEATURE SUMMARY

,count,mean,std,min,25%,50%,75%,max
bd_brand_in_url,131167.0,0.001639,0.040453,0.0,0.0,0.0,0.0,1.0
bd_brand_in_sub_not_domain,131167.0,0.000236,0.015372,0.0,0.0,0.0,0.0,1.0
bd_brand_in_path_not_domain,131167.0,0.000046,0.006763,0.0,0.0,0.0,0.0,1.0
min_brand_edit_distance,131167.0,7.933825,4.364038,0.0,5.0,7.0,10.0,99.0
digit_substitution_score,131167.0,0.143413,0.505035,0.0,0.0,0.0,0.0,25.0
is_typosquatting,131167.0,0.008158,0.089950,0.0,0.0,0.0,0.0,1.0
new_brand_in_query,131167.0,0.000069,0.008283,0.0,0.0,0.0,0.0,1.0

5. URL COUNTS WITH BRAND FLAGS
bd_brand_in_url: 215
bd_brand_in_sub_not_domain: 31
bd_brand_in_path_not_domain: 6
is_typosquatting: 1070
new_brand_in_query: 9

In [ ]:
# STEP 3: Check label meaning and brand-related features

print("1. SAMPLE URLs FROM EACH LABEL")

for label_value in sorted(phishbd_df["label"].unique()):
    print(f"\nLabel {label_value} — 10 example URLs:")
    display(
        phishbd_df.loc[
            phishbd_df["label"] == label_value, ["url", "label"]
        ].head(10)
    )

brand_features = [
    "bd_brand_in_url",
    "bd_brand_in_sub_not_domain",
    "bd_brand_in_path_not_domain",
    "is_typosquatting",
    "new_brand_in_query"
]

print("\n2. BRAND FEATURE AVERAGES FOR EACH LABEL")
display(
    phishbd_df.groupby("label")[brand_features]
    .mean()
    .round(4)
)

print("\n3. EXAMPLES FLAGGED AS TYPOSQUATTING")
display(
    phishbd_df.loc[
        phishbd_df["is_typosquatting"] == 1,
        ["url", "label", "min_brand_edit_distance",
         "digit_substitution_score", "is_typosquatting"]
    ].head(15)
)

print("\n4. EXAMPLES FLAGGED WITH A BANGLADESH BRAND")
display(
    phishbd_df.loc[
        phishbd_df["bd_brand_in_url"] == 1,
        ["url", "label", "bd_brand_in_url"]
    ].head(15)
)

1. SAMPLE URLs FROM EACH LABEL

Label 0 — 10 example URLs:

                                  url  label
13                     http://vk.team      0
14              http://evvelcevap.com      0
17              https://fmshosted.com      0
21  https://constructionspecifier.com      0
22                  http://golang.org      0
26                  http://betpawa.mw      0
38                   http://google.es      0
44              https://alltribes.com      0
47             http://afilias-nst.org      0
51               https://aafda.gov.et      0

Label 1 — 10 example URLs:

                                                 url  label
0  http://www.au-payccoy.aseacaameoy.tvxp.top/AU/...      1
1                 http://hkpgk.the-drone-company.com      1
2                             http://marconishop.com      1
3                           http://stage-coingeb.com      1
4                     http://xgiqfrqcebklsdsyy.click      1
5                                  http://faywho.com      1
6                    http://customeremailsupport.com      1
7                           http://www.pauleames.com      1
8                                  http://xqpxkkx.cn      1
9                       http://bimcellcumartesii.com      1

2. BRAND FEATURE AVERAGES FOR EACH LABEL

,bd_brand_in_url,bd_brand_in_sub_not_domain,bd_brand_in_path_not_domain,is_typosquatting,new_brand_in_query
label,,,,,
0,0.0014,0.0000,0.0000,0.0165,0.0000
1,0.0017,0.0003,0.0001,0.0046,0.0001

3. EXAMPLES FLAGGED AS TYPOSQUATTING

,url,label,min_brand_edit_distance,digit_substitution_score,is_typosquatting
125,https://tapad.com,0,2.0,0.0,1
179,https://mgbw.com,0,2.0,0.0,1
208,https://6pay.top,0,1.0,0.0,1
250,http://whatsapl.com,1,1.0,0.0,1
471,https://vtc.edu.hk,0,2.0,0.0,1
498,https://rhi.com,0,2.0,0.0,1
552,https://www.gmailaccount.mikronsoft.com,1,2.0,0.0,1
561,https://sts.parts,0,2.0,0.0,1
607,https://bma.org.uk,0,2.0,0.0,1
665,https://grc.ca,0,2.0,0.0,1
736,http://epaypal.xyz,1,1.0,0.0,1
883,http://wyhatsapp.com,1,1.0,0.0,1
921,https://magrabi.com,0,2.0,0.0,1
940,https://cpad.gov.cn,0,2.0,0.0,1
985,https://nyq.cn,0,2.0,0.0,1

4. EXAMPLES FLAGGED WITH A BANGLADESH BRAND

,url,label,bd_brand_in_url
1266,http://www.ekl-net.com-asoceesnesas.mtbuiy.top...,1,1
2390,http://secure01mtb.com,1,1
3099,https://imbracamintesimpla.ro,0,1
3379,https://rockethard.com.ar,0,1
3632,http://connect-brtaccount.com,1,1
5899,http://robimprove.coddes.top,1,1
6319,http://mtbbon1ine.com,1,1
6406,http://3mtbverify.com,1,1
7186,https://ganpatifinances.loan/?cep=CpbKqYthDlcb...,1,1
8268,http://3mtbsecureverify.com,1,1
8592,http://robinsontaylor.com,1,1
9305,http://online3mtbverify.com,1,1
9673,http://www.secure01mtb.com,1,1
9758,https://islamicbook.ws,0,1
10113,https://mtbsupporto9line.firebaseapp.com/,1,1

In [ ]:
# STEP 4: Check feature flags against dataset labels

features_to_check = [
    "bd_brand_in_url",
    "bd_brand_in_sub_not_domain",
    "bd_brand_in_path_not_domain",
    "is_typosquatting",
    "new_brand_in_query"
]

for feature in features_to_check:
    print(f"\n--- {feature} ---")

    # Count label 0 and label 1 for URLs flagged by this feature
    flagged = phishbd_df[phishbd_df[feature] == 1]
    print("Number of flagged URLs:", len(flagged))

    if len(flagged) > 0:
        print("\nLabel counts among flagged URLs:")
        print(flagged["label"].value_counts().sort_index())

        print("\nPercentage of each label among flagged URLs:")
        print(
            (flagged["label"].value_counts(normalize=True).sort_index() * 100)
            .round(2)
        )

print("\n--- Label mapping confirmation ---")
print("Please check the dataset documentation for the official meanings")
print("of label 0 and label 1.")

--- bd_brand_in_url ---
Number of flagged URLs: 215

Label counts among flagged URLs:
label
0     56
1    159
Name: count, dtype: int64

Percentage of each label among flagged URLs:
label
0    26.05
1    73.95
Name: proportion, dtype: float64

--- bd_brand_in_sub_not_domain ---
Number of flagged URLs: 31

Label counts among flagged URLs:
label
1    31
Name: count, dtype: int64

Percentage of each label among flagged URLs:
label
1    100.0
Name: proportion, dtype: float64

--- bd_brand_in_path_not_domain ---
Number of flagged URLs: 6

Label counts among flagged URLs:
label
1    6
Name: count, dtype: int64

Percentage of each label among flagged URLs:
label
1    100.0
Name: proportion, dtype: float64

--- is_typosquatting ---
Number of flagged URLs: 1070

Label counts among flagged URLs:
label
0    648
1    422
Name: count, dtype: int64

Percentage of each label among flagged URLs:
label
0    60.56
1    39.44
Name: proportion, dtype: float64

--- new_brand_in_query ---
Number of flagged URLs: 9

Label counts among flagged URLs:
label
1    9
Name: count, dtype: int64

Percentage of each label among flagged URLs:
label
1    100.0
Name: proportion, dtype: float64

--- Label mapping confirmation ---
Please check the dataset documentation for the official meanings
of label 0 and label 1.

In [ ]:
# STEP 5: Inspect features that match the current TinyPhish model

feature_mapping = {
    "URL length": "url_length",
    "Number of dots": "dot_count",
    "Number of hyphens": "hyphen_count",
    "HTTPS indicator": "is_https",
    "@ symbol indicator": "at_count",
    "Number of digits": "digit_count",
    "Number of slashes": "slash_count",
    "IP address indicator": "has_ip"
}

for description, column in feature_mapping.items():
    print(f"\n{description} ({column})")

    print("Data type:", phishbd_df[column].dtype)
    print("Missing values:", phishbd_df[column].isna().sum())
    print("Minimum:", phishbd_df[column].min())
    print("Maximum:", phishbd_df[column].max())

print("\n--- Feature comparison by label ---")

columns_to_compare = list(feature_mapping.values())

display(
    phishbd_df.groupby("label")[columns_to_compare]
    .mean()
    .round(3)
)

URL length (url_length)
Data type: float64
Missing values: 0
Minimum: 11.0
Maximum: 492.0

Number of dots (dot_count)
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 24.0

Number of hyphens (hyphen_count)
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 20.0

HTTPS indicator (is_https)
Data type: int64
Missing values: 0
Minimum: 0
Maximum: 1

@ symbol indicator (at_count)
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 4.0

Number of digits (digit_count)
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 200.0

Number of slashes (slash_count)
Data type: float64
Missing values: 0
Minimum: 2.0
Maximum: 21.0

IP address indicator (has_ip)
Data type: int64
Missing values: 0
Minimum: 0
Maximum: 1

--- Feature comparison by label ---

,url_length,dot_count,hyphen_count,is_https,at_count,digit_count,slash_count,has_ip
label,,,,,,,,
0,21.026,1.102,0.108,0.746,0.000,0.243,2.000,0.000
1,32.417,1.892,0.481,0.026,0.001,1.750,2.335,0.007

In [ ]:
# STEP 6: Train an experimental model on PhishBD_2026
# This does NOT replace the current Android model.

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Keep the same eight features used by TinyPhish.
# Convert at_count into the binary has_at feature.
X = pd.DataFrame({
    "url_length": phishbd_df["url_length"],
    "num_dots": phishbd_df["dot_count"],
    "num_hyphens": phishbd_df["hyphen_count"],
    "has_https": phishbd_df["is_https"],
    "has_at": (phishbd_df["at_count"] > 0).astype(int),
    "num_digits": phishbd_df["digit_count"],
    "num_slashes": phishbd_df["slash_count"],
    "has_ip": phishbd_df["has_ip"]
})

y = phishbd_df["label"].astype(int)

# Reserve 20% of the data for testing.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Train a small decision tree, matching the current depth limit.
model_bd_baseline = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

model_bd_baseline.fit(X_train, y_train)

# Predict on the held-out test set.
y_pred = model_bd_baseline.predict(X_test)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Model depth:", model_bd_baseline.get_depth())
print("Model leaves:", model_bd_baseline.get_n_leaves())

print("\n--- Evaluation results ---")
print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Precision:", round(precision_score(y_test, y_pred, zero_division=0), 4))
print("Recall:", round(recall_score(y_test, y_pred, zero_division=0), 4))
print("F1-score:", round(f1_score(y_test, y_pred, zero_division=0), 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred, labels=[0, 1]))

print("\nClassification report:")
print(classification_report(
    y_test,
    y_pred,
    labels=[0, 1],
    target_names=["Legitimate (0)", "Phishing (1)"],
    zero_division=0
))

Training rows: 104933
Testing rows: 26234
Model depth: 10
Model leaves: 324

--- Evaluation results ---
Accuracy: 0.9238
Precision: 0.9579
Recall: 0.9322
F1-score: 0.9449

Confusion matrix:
[[ 7117   753]
 [ 1245 17119]]

Classification report:
                precision    recall  f1-score   support

Legitimate (0)       0.85      0.90      0.88      7870
  Phishing (1)       0.96      0.93      0.94     18364

      accuracy                           0.92     26234
     macro avg       0.90      0.92      0.91     26234
  weighted avg       0.93      0.92      0.92     26234

In [ ]:
# STEP 7: Train and evaluate a 73-feature experimental model
# This does NOT change the existing Android app or JSON model.

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)
from sklearn.model_selection import train_test_split

# Use all 73 feature columns.
# Exclude the raw URL and label columns.
X_all = phishbd_df.drop(columns=["url", "label"])
y_all = phishbd_df["label"].astype(int)

print("Number of features:", X_all.shape[1])
print("Missing feature values:", X_all.isna().sum().sum())

# Use the same 80:20 stratified split settings.
X_train_all, X_test_all, y_train_all, y_test_all = train_test_split(
    X_all,
    y_all,
    test_size=0.20,
    random_state=42,
    stratify=y_all
)

# Train a tree with the same depth and class weighting.
model_bd_73 = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

model_bd_73.fit(X_train_all, y_train_all)

pred_73 = model_bd_73.predict(X_test_all)

# Display results for comparison.
print("\n--- 73-FEATURE MODEL ---")
print("Training rows:", len(X_train_all))
print("Testing rows:", len(X_test_all))
print("Model depth:", model_bd_73.get_depth())
print("Model leaves:", model_bd_73.get_n_leaves())

print("Accuracy:", round(accuracy_score(y_test_all, pred_73), 4))
print("Precision:", round(
    precision_score(y_test_all, pred_73, zero_division=0), 4
))
print("Recall:", round(
    recall_score(y_test_all, pred_73, zero_division=0), 4
))
print("F1-score:", round(
    f1_score(y_test_all, pred_73, zero_division=0), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_all, pred_73, labels=[0, 1]))

print("\n--- COMPARISON WITH 8-FEATURE MODEL ---")
print("Metric          8 features    73 features")
print(
    f"Accuracy        "
    f"{accuracy_score(y_test, y_pred):.4f}        "
    f"{accuracy_score(y_test_all, pred_73):.4f}"
)
print(
    f"Precision       "
    f"{precision_score(y_test, y_pred, zero_division=0):.4f}        "
    f"{precision_score(y_test_all, pred_73, zero_division=0):.4f}"
)
print(
    f"Recall          "
    f"{recall_score(y_test, y_pred, zero_division=0):.4f}        "
    f"{recall_score(y_test_all, pred_73, zero_division=0):.4f}"
)
print(
    f"F1-score        "
    f"{f1_score(y_test, y_pred, zero_division=0):.4f}        "
    f"{f1_score(y_test_all, pred_73, zero_division=0):.4f}"
)

Number of features: 73
Missing feature values: 0

--- 73-FEATURE MODEL ---
Training rows: 104933
Testing rows: 26234
Model depth: 10
Model leaves: 226
Accuracy: 0.9422
Precision: 0.968
Recall: 0.9488
F1-score: 0.9583

Confusion matrix:
[[ 7294   576]
 [  940 17424]]

--- COMPARISON WITH 8-FEATURE MODEL ---
Metric          8 features    73 features
Accuracy        0.9238        0.9422
Precision       0.9579        0.9680
Recall          0.9322        0.9488
F1-score        0.9449        0.9583

In [ ]:
# STEP 8: Inspect feature importance and actual feature usage

import pandas as pd
import numpy as np

# Rank all 73 features by importance
importance_df = pd.DataFrame({
    "feature": X_all.columns,
    "importance": model_bd_73.feature_importances_
}).sort_values("importance", ascending=False)

print("TOP 20 FEATURES")
display(importance_df.head(20).round(5))

# Find features actually used in the decision tree's split rules
used_feature_indices = np.unique(
    model_bd_73.tree_.feature[
        model_bd_73.tree_.feature >= 0
    ]
)

used_features = X_all.columns[used_feature_indices].tolist()

print("\nFEATURE USAGE SUMMARY")
print("Total available features:", X_all.shape[1])
print("Features actually used by tree:", len(used_features))
print("Features not used by tree:", X_all.shape[1] - len(used_features))

print("\nFEATURES ACTUALLY USED")
print(used_features)

print("\nTREE SIZE")
print("Number of tree nodes:", model_bd_73.tree_.node_count)
print("Maximum depth:", model_bd_73.get_depth())

TOP 20 FEATURES

                    feature  importance
25             cv_ratio_url     0.71948
0                url_length     0.17486
57              is_free_tld     0.02294
34         tld_count_in_url     0.01616
13              digit_count     0.01506
19               tld_length     0.01044
27    longest_consonant_run     0.00806
21             letter_ratio     0.00428
23           entropy_domain     0.00398
37   new_domain_vowel_ratio     0.00315
29         avg_token_length     0.00257
48     has_suspicious_words     0.00246
2          subdomain_length     0.00226
22              entropy_url     0.00197
30         max_token_length     0.00195
5                 dot_count     0.00142
1             domain_length     0.00142
14             letter_count     0.00137
15       special_char_count     0.00137
32  min_brand_edit_distance     0.00109

FEATURE USAGE SUMMARY
Total available features: 73
Features actually used by tree: 34
Features not used by tree: 39

FEATURES ACTUALLY USED
['url_length', 'domain_length', 'subdomain_length', 'path_length', 'dot_count', 'hyphen_count', 'digit_count', 'letter_count', 'special_char_count', 'subdomain_count', 'tld_length', 'digit_ratio', 'letter_ratio', 'entropy_url', 'entropy_domain', 'cv_ratio_url', 'cv_ratio_domain', 'longest_consonant_run', 'token_count', 'avg_token_length', 'max_token_length', 'min_brand_edit_distance', 'digit_substitution_score', 'tld_count_in_url', 'consec_digits_domain', 'new_domain_vowel_ratio', 'new_url_digit_letter_ratio', 'has_ip', 'has_http_in_domain', 'has_suspicious_words', 'domain_has_hyphen', 'is_free_tld', 'is_typosquatting', 'has_punycode']

TREE SIZE
Number of tree nodes: 451
Maximum depth: 10

In [ ]:
# STEP 9: Test the 73-feature model without cv_ratio_url

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Remove only cv_ratio_url
X_without_cv = X_all.drop(columns=["cv_ratio_url"])

# Use the same train/test split
X_train_cv, X_test_cv, y_train_cv, y_test_cv = train_test_split(
    X_without_cv,
    y_all,
    test_size=0.20,
    random_state=42,
    stratify=y_all
)

# Train the experimental model
model_without_cv = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

model_without_cv.fit(X_train_cv, y_train_cv)
pred_without_cv = model_without_cv.predict(X_test_cv)

# Calculate metrics
acc = accuracy_score(y_test_cv, pred_without_cv)
prec = precision_score(y_test_cv, pred_without_cv, zero_division=0)
rec = recall_score(y_test_cv, pred_without_cv, zero_division=0)
f1 = f1_score(y_test_cv, pred_without_cv, zero_division=0)

print("Features available:", X_without_cv.shape[1])
print("Model depth:", model_without_cv.get_depth())
print("Model leaves:", model_without_cv.get_n_leaves())

print("\n--- RESULTS WITHOUT cv_ratio_url ---")
print("Accuracy:", round(acc, 4))
print("Precision:", round(prec, 4))
print("Recall:", round(rec, 4))
print("F1-score:", round(f1, 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_cv, pred_without_cv, labels=[0, 1]))

print("\n--- COMPARISON ---")
print("Metric          With feature    Without feature")
print(
    f"Accuracy        {accuracy_score(y_test_all, pred_73):.4f}"
    f"          {acc:.4f}"
)
print(
    f"Precision       {precision_score(y_test_all, pred_73):.4f}"
    f"          {prec:.4f}"
)
print(
    f"Recall          {recall_score(y_test_all, pred_73):.4f}"
    f"          {rec:.4f}"
)
print(
    f"F1-score        {f1_score(y_test_all, pred_73):.4f}"
    f"          {f1:.4f}"
)

Features available: 72
Model depth: 10
Model leaves: 256

--- RESULTS WITHOUT cv_ratio_url ---
Accuracy: 0.944
Precision: 0.9684
Recall: 0.9511
F1-score: 0.9597

Confusion matrix:
[[ 7300   570]
 [  898 17466]]

--- COMPARISON ---
Metric          With feature    Without feature
Accuracy        0.9422          0.9440
Precision       0.9680          0.9684
Recall          0.9488          0.9511
F1-score        0.9583          0.9597

In [ ]:
# STEP 10: Find which features the model uses without cv_ratio_url

import numpy as np
import pandas as pd

used_indices = np.unique(
    model_without_cv.tree_.feature[
        model_without_cv.tree_.feature >= 0
    ]
)

used_features_without_cv = X_without_cv.columns[used_indices].tolist()

print("Available features:", X_without_cv.shape[1])
print("Features actually used:", len(used_features_without_cv))
print("Tree nodes:", model_without_cv.tree_.node_count)
print("Tree depth:", model_without_cv.get_depth())

print("\nFeatures actually used:")
for feature in used_features_without_cv:
    print(feature)

print("\nBangladesh-related features used:")
bd_features_used = [
    feature for feature in used_features_without_cv
    if feature.startswith("bd_")
    or "brand" in feature
    or "typosquatting" in feature
    or "is_bd_tld" in feature
    or "new_tld_is_bd" in feature
]

print(bd_features_used if bd_features_used else "None")

Available features: 72
Features actually used: 35
Tree nodes: 511
Tree depth: 10

Features actually used:
url_length
domain_length
subdomain_length
path_length
dot_count
hyphen_count
slash_count
digit_count
letter_count
special_char_count
subdomain_count
tld_length
digit_ratio
letter_ratio
entropy_url
entropy_domain
cv_ratio_domain
longest_consonant_run
token_count
avg_token_length
max_token_length
numeric_token_count
min_brand_edit_distance
digit_substitution_score
tld_count_in_url
consec_digits_domain
new_domain_vowel_ratio
new_url_digit_letter_ratio
is_https
has_http_in_domain
has_suspicious_words
is_free_tld
is_typosquatting
has_punycode
has_base64

Bangladesh-related features used:
['min_brand_edit_distance', 'is_typosquatting']

In [ ]:
# STEP 11: Measure experimental model size

import joblib
import os

model_path = "/content/tinyphish_phishbd_experiment.joblib"

joblib.dump(model_without_cv, model_path)

size_bytes = os.path.getsize(model_path)

print("Saved model:", model_path)
print("Model size in bytes:", size_bytes)
print("Model size in KB:", round(size_bytes / 1024, 2))
print("Model size in MB:", round(size_bytes / (1024 * 1024), 4))
print("Under 1 MB:", size_bytes < 1024 * 1024)

Saved model: /content/tinyphish_phishbd_experiment.joblib
Model size in bytes: 43753
Model size in KB: 42.73
Model size in MB: 0.0417
Under 1 MB: True

In [ ]:
# STEP 12: Inspect how cv_ratio_domain behaves

print("cv_ratio_domain data type:", phishbd_df["cv_ratio_domain"].dtype)
print("Missing values:", phishbd_df["cv_ratio_domain"].isna().sum())

print("\nSummary by label:")
display(
    phishbd_df.groupby("label")["cv_ratio_domain"]
    .describe()
    .round(4)
)

print("\nSample URLs and cv_ratio_domain values:")
display(
    phishbd_df[
        ["url", "label", "cv_ratio_domain"]
    ].sample(10, random_state=42)
)

cv_ratio_domain data type: float64
Missing values: 0

Summary by label:

         count    mean     std  min     25%     50%   75%   max
label
0      39350.0  1.6461  1.1694  0.0  0.8000  1.4000  2.00  22.0
1      91817.0  0.6556  0.1807  0.0  0.5714  0.6667  0.75   1.0

Sample URLs and cv_ratio_domain values:

,url,label,cv_ratio_domain
89775,http://shpagat.space,1,0.7143
23129,https://humanitarianaction.info,0,1.0000
11405,http://elokaybrand.com,1,0.6364
58072,https://tumejorweb.davlenda.repl.co/,1,0.7500
75100,https://pornotarado.com,0,1.2000
7095,http://hindawi.com,0,0.5714
44626,http://www.ekl-net.com-asocesnesas.vcuu.top/jp...,1,0.5000
18649,http://www.au-poyacy.acuoaaoaeoy.cuch.top/AU/p...,1,0.7500
41359,http://autohandel-banaszek.pl,1,0.5556
53671,http://vonedge.com,0,0.5714

In [ ]:
# STEP 13: Test the model without cv_ratio_domain

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Remove cv_ratio_domain from the training and testing data
X_train_no_cv_domain = X_train_cv.drop(
    columns=["cv_ratio_domain"]
)

X_test_no_cv_domain = X_test_cv.drop(
    columns=["cv_ratio_domain"]
)

# Train a new experimental model
model_no_cv_domain = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

model_no_cv_domain.fit(
    X_train_no_cv_domain,
    y_train_cv
)

# Make predictions
pred_no_cv_domain = model_no_cv_domain.predict(
    X_test_no_cv_domain
)

# Display evaluation results
print("Accuracy:", round(
    accuracy_score(y_test_cv, pred_no_cv_domain), 4
))
print("Precision:", round(
    precision_score(y_test_cv, pred_no_cv_domain), 4
))
print("Recall:", round(
    recall_score(y_test_cv, pred_no_cv_domain), 4
))
print("F1-score:", round(
    f1_score(y_test_cv, pred_no_cv_domain), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_cv, pred_no_cv_domain))

print("\nNumber of features:", X_train_no_cv_domain.shape[1])
print("Model depth:", model_no_cv_domain.get_depth())
print("Number of leaves:", model_no_cv_domain.get_n_leaves())

Accuracy: 0.9433
Precision: 0.9684
Recall: 0.9501
F1-score: 0.9591

Confusion matrix:
[[ 7300   570]
 [  917 17447]]

Number of features: 71
Model depth: 10
Number of leaves: 267

In [ ]:
# STEP 14: Inspect important features in the 71-feature model

import pandas as pd

importance_df = pd.DataFrame({
    "Feature": X_train_no_cv_domain.columns,
    "Importance": model_no_cv_domain.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("Top 15 most important features:")
display(importance_df.head(15).round(5))

print("\nBangladesh-related features:")
display(
    importance_df[
        importance_df["Feature"].str.contains(
            "bd_brand|bd_gov|brand|typosquatting|new_tld_is_bd",
            case=False,
            regex=True
        )
    ].round(5)
)

Top 15 most important features:

                   Feature  Importance
40                is_https     0.65377
0               url_length     0.17298
3              path_length     0.05032
55             is_free_tld     0.02449
32        tld_count_in_url     0.01657
20             digit_ratio     0.01511
25   longest_consonant_run     0.01268
19              tld_length     0.01061
21            letter_ratio     0.00663
2         subdomain_length     0.00654
23          entropy_domain     0.00479
35  new_domain_vowel_ratio     0.00341
16         subdomain_count     0.00298
46    has_suspicious_words     0.00276
1            domain_length     0.00266

Bangladesh-related features:

                        Feature  Importance
30      min_brand_edit_distance     0.00126
58             is_typosquatting     0.00065
51              bd_brand_in_url     0.00003
54               bd_gov_keyword     0.00000
53  bd_brand_in_path_not_domain     0.00000
52   bd_brand_in_sub_not_domain     0.00000
57            bd_brand_free_tld     0.00000
66                new_tld_is_bd     0.00000
67           new_brand_in_query     0.00000

In [ ]:
# STEP 15: Investigate HTTPS distribution by label

print("HTTPS distribution by label (row percentages):")

display(
    pd.crosstab(
        phishbd_df["label"],
        phishbd_df["is_https"],
        normalize="index"
    ).mul(100).round(2)
)

print("\nLabel meaning:")
print("0 = Legitimate")
print("1 = Phishing")

print("\nRaw counts:")
display(
    pd.crosstab(
        phishbd_df["label"],
        phishbd_df["is_https"]
    )
)

HTTPS distribution by label (row percentages):

is_https      0      1
label
0         25.41  74.59
1         97.41   2.59

Label meaning:
0 = Legitimate
1 = Phishing

Raw counts:

is_https      0      1
label
0         10000  29350
1         89440   2377

In [ ]:
# STEP 17: Test the 70-feature model without is_https

X_train_no_https = X_train_no_cv_domain.drop(
    columns=["is_https"]
)

X_test_no_https = X_test_no_cv_domain.drop(
    columns=["is_https"]
)

model_no_https = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

model_no_https.fit(
    X_train_no_https,
    y_train_cv
)

pred_no_https = model_no_https.predict(
    X_test_no_https
)

print("Accuracy:", round(
    accuracy_score(y_test_cv, pred_no_https), 4
))
print("Precision:", round(
    precision_score(y_test_cv, pred_no_https), 4
))
print("Recall:", round(
    recall_score(y_test_cv, pred_no_https), 4
))
print("F1-score:", round(
    f1_score(y_test_cv, pred_no_https), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_cv, pred_no_https))

print("\nNumber of features:", X_train_no_https.shape[1])
print("Model depth:", model_no_https.get_depth())
print("Number of leaves:", model_no_https.get_n_leaves())

Accuracy: 0.8495
Precision: 0.976
Recall: 0.8048
F1-score: 0.8822

Confusion matrix:
[[ 7506   364]
 [ 3584 14780]]

Number of features: 70
Model depth: 10
Number of leaves: 249

In [ ]:
# STEP 19: Evaluate the HTTPS-only rule on the same test set

https_only_pred = (
    1 - X_test_cv["is_https"]
).astype(int)

print("HTTPS-only rule")
print("Accuracy:", round(
    accuracy_score(y_test_cv, https_only_pred), 4
))
print("Precision:", round(
    precision_score(y_test_cv, https_only_pred), 4
))
print("Recall:", round(
    recall_score(y_test_cv, https_only_pred), 4
))
print("F1-score:", round(
    f1_score(y_test_cv, https_only_pred), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_cv, https_only_pred))

HTTPS-only rule
Accuracy: 0.9068
Precision: 0.9015
Recall: 0.9733
F1-score: 0.936

Confusion matrix:
[[ 5916  1954]
 [  490 17874]]

In [ ]:
# STEP 21: Check whether domains overlap between training and testing

from urllib.parse import urlparse
import pandas as pd

def get_domain(url):
    url = str(url)
    parsed = urlparse(url if "://" in url else "//" + url)
    return (parsed.hostname or "").lower()

train_domains = set(
    phishbd_df.loc[X_train_cv.index, "url"].apply(get_domain)
)

test_domains = set(
    phishbd_df.loc[X_test_cv.index, "url"].apply(get_domain)
)

overlap_domains = train_domains.intersection(test_domains)

print("Unique training domains:", len(train_domains))
print("Unique testing domains:", len(test_domains))
print("Domains appearing in both sets:", len(overlap_domains))
print(
    "Percentage of test domains also in training:",
    round(
        100 * len(overlap_domains) / max(len(test_domains), 1),
        2
    ),
    "%"
)

Unique training domains: 102681
Unique testing domains: 26004
Domains appearing in both sets: 840
Percentage of test domains also in training: 3.23 %

In [ ]:
# STEP 22: Evaluate the model on unseen hostnames

import pandas as pd
from urllib.parse import urlparse
from sklearn.model_selection import GroupShuffleSplit
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# 1. Get the hostname from each URL
def get_hostname(url):
    url = str(url)
    parsed = urlparse(
        url if "://" in url else "//" + url
    )
    return (parsed.hostname or "").lower()

groups = phishbd_df["url"].apply(get_hostname)

# 2. Use 71 features, excluding both cv_ratio features
X_71 = X_all.drop(
    columns=["cv_ratio_url", "cv_ratio_domain"]
)

y = y_all

# 3. Split by hostname, not by individual URL
splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    splitter.split(X_71, y, groups=groups)
)

X_train_group = X_71.iloc[train_idx]
X_test_group = X_71.iloc[test_idx]
y_train_group = y.iloc[train_idx]
y_test_group = y.iloc[test_idx]

# 4. Confirm that hostnames do not overlap
train_hosts = set(groups.iloc[train_idx])
test_hosts = set(groups.iloc[test_idx])

print("Training URLs:", len(train_idx))
print("Testing URLs:", len(test_idx))
print("Training hostnames:", len(train_hosts))
print("Testing hostnames:", len(test_hosts))
print("Overlapping hostnames:", len(train_hosts & test_hosts))

# 5. Train the experimental model
group_model = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

group_model.fit(X_train_group, y_train_group)

# 6. Evaluate on unseen hostnames
group_pred = group_model.predict(X_test_group)

print("\nDOMAIN-GROUPED EVALUATION RESULTS")
print("Accuracy:", round(
    accuracy_score(y_test_group, group_pred), 4
))
print("Precision:", round(
    precision_score(y_test_group, group_pred, zero_division=0), 4
))
print("Recall:", round(
    recall_score(y_test_group, group_pred, zero_division=0), 4
))
print("F1-score:", round(
    f1_score(y_test_group, group_pred, zero_division=0), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_group, group_pred))

print("\nTree depth:", group_model.get_depth())
print("Number of leaves:", group_model.get_n_leaves())

Training URLs: 104940
Testing URLs: 26227
Training hostnames: 102276
Testing hostnames: 25569
Overlapping hostnames: 0

DOMAIN-GROUPED EVALUATION RESULTS
Accuracy: 0.942
Precision: 0.9671
Recall: 0.9496
F1-score: 0.9583

Confusion matrix:
[[ 7234   594]
 [  928 17471]]

Tree depth: 10
Number of leaves: 254

In [ ]:
!pip -q install tldextract

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.5/107.5 kB 864.7 kB/s eta 0:00:00

In [ ]:
# STEP 25: Evaluate on completely unseen registered domains

import pandas as pd
import tldextract

from sklearn.model_selection import GroupShuffleSplit
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# 1. Extract registered domains
extractor = tldextract.TLDExtract()

def get_registered_domain(url):
    url = str(url)
    parsed = urlparse(
        url if "://" in url else "//" + url
    )
    hostname = parsed.hostname or ""

    if not hostname:
        return ""

    result = extractor(hostname)
    return ".".join(
        part for part in [
            result.domain,
            result.suffix
        ] if part
    )

groups_registered = phishbd_df["url"].apply(
    get_registered_domain
)

# 2. Remove URLs whose registered domain could not be extracted
valid = groups_registered != ""

X_domain = X_all.drop(
    columns=["cv_ratio_url", "cv_ratio_domain"]
).loc[valid]

y_domain = y_all.loc[valid]
groups_domain = groups_registered.loc[valid]

# 3. Split by registered domain
splitter_domain = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx_d, test_idx_d = next(
    splitter_domain.split(
        X_domain,
        y_domain,
        groups=groups_domain
    )
)

X_train_d = X_domain.iloc[train_idx_d]
X_test_d = X_domain.iloc[test_idx_d]
y_train_d = y_domain.iloc[train_idx_d]
y_test_d = y_domain.iloc[test_idx_d]

train_domains = set(groups_domain.iloc[train_idx_d])
test_domains = set(groups_domain.iloc[test_idx_d])

print("Training URLs:", len(train_idx_d))
print("Testing URLs:", len(test_idx_d))
print("Training registered domains:", len(train_domains))
print("Testing registered domains:", len(test_domains))
print("Overlapping registered domains:",
      len(train_domains & test_domains))

# 4. Train the model
registered_domain_model = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

registered_domain_model.fit(X_train_d, y_train_d)

# 5. Evaluate
pred_domain = registered_domain_model.predict(X_test_d)

print("\nREGISTERED-DOMAIN EVALUATION")
print("Accuracy:", round(
    accuracy_score(y_test_d, pred_domain), 4
))
print("Precision:", round(
    precision_score(y_test_d, pred_domain, zero_division=0), 4
))
print("Recall:", round(
    recall_score(y_test_d, pred_domain, zero_division=0), 4
))
print("F1-score:", round(
    f1_score(y_test_d, pred_domain, zero_division=0), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_d, pred_domain))

print("\nTree depth:", registered_domain_model.get_depth())
print("Number of leaves:",
      registered_domain_model.get_n_leaves())

Training URLs: 104937
Testing URLs: 26230
Training registered domains: 79908
Testing registered domains: 19978
Overlapping registered domains: 0

REGISTERED-DOMAIN EVALUATION
Accuracy: 0.9418
Precision: 0.9649
Recall: 0.9515
F1-score: 0.9582

Confusion matrix:
[[ 7224   635]
 [  891 17480]]

Tree depth: 10
Number of leaves: 279

In [ ]:
# STEP 26: Inspect the available dataset and features
# This cell only displays information; it does not change the model.

print("Dataset shape:", phishbd_df.shape)
print("X_all shape:", X_all.shape)
print("y_all shape:", y_all.shape)

print("\nFeature columns:")
print(X_all.columns.tolist())

print("\nTarget class counts:")
print(y_all.value_counts())

print("\nRegistered-domain split sizes:")
print("Training samples:", len(X_train_d))
print("Testing samples:", len(X_test_d))

print("\nTraining and testing feature columns match:",
      X_train_d.columns.equals(X_test_d.columns))

Dataset shape: (131167, 75)
X_all shape: (131167, 73)
y_all shape: (131167,)

Feature columns:
['url_length', 'domain_length', 'subdomain_length', 'path_length', 'query_length', 'dot_count', 'hyphen_count', 'underscore_count', 'slash_count', 'at_count', 'eq_count', 'amp_count', 'percent_count', 'digit_count', 'letter_count', 'special_char_count', 'subdomain_count', 'path_depth', 'query_param_count', 'tld_length', 'digit_ratio', 'letter_ratio', 'entropy_url', 'entropy_domain', 'entropy_subdomain', 'cv_ratio_url', 'cv_ratio_domain', 'longest_consonant_run', 'token_count', 'avg_token_length', 'max_token_length', 'numeric_token_count', 'min_brand_edit_distance', 'digit_substitution_score', 'tld_count_in_url', 'consec_digits_domain', 'new_path_token_entropy', 'new_domain_vowel_ratio', 'new_query_key_count', 'new_susp_word_count', 'new_url_digit_letter_ratio', 'has_ip', 'is_https', 'has_at', 'has_double_slash', 'has_port', 'is_shortened', 'has_http_in_domain', 'has_suspicious_words', 'domain_has_digit', 'domain_has_hyphen', 'has_fragment', 'has_repeated_tokens', 'bd_brand_in_url', 'bd_brand_in_sub_not_domain', 'bd_brand_in_path_not_domain', 'bd_gov_keyword', 'is_free_tld', 'is_bd_tld', 'bd_brand_free_tld', 'is_typosquatting', 'has_repeated_chars', 'has_punycode', 'has_redirect_param', 'has_base64', 'multiple_tlds', 'has_hex_encoding', 'has_login_path', 'new_tld_is_bd', 'new_brand_in_query', 'new_has_encoded_chars', 'new_path_has_exe', 'new_subdomain_is_ip_like']

Target class counts:
label
1    91817
0    39350
Name: count, dtype: int64

Registered-domain split sizes:
Training samples: 104937
Testing samples: 26230

Training and testing feature columns match: True

In [ ]:

# STEP 26.1: Compare Logistic Regression, Decision Tree, and Random Forest
# Uses the eight features supported by the TinyPhish Android app.
# This experiment does NOT overwrite the existing final model.

from sklearn.model_selection import GroupShuffleSplit

# 1. Select the eight Android-compatible features.
# These are the equivalent feature names in this dataset.
android_features = [
    "url_length",
    "dot_count",
    "hyphen_count",
    "is_https",
    "at_count",
    "digit_count",
    "slash_count",
    "has_ip"
]

X_compare = X_domain[android_features].copy()
y_compare = y_domain.copy()
groups_compare = groups_domain.copy()

# 2. Create one shared split by registered domain.
# No registered domain should appear in both sets.
comparison_splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_compare_idx, test_compare_idx = next(
    comparison_splitter.split(
        X_compare,
        y_compare,
        groups=groups_compare
    )
)

X_train_compare = X_compare.iloc[train_compare_idx]
X_test_compare = X_compare.iloc[test_compare_idx]
y_train_compare = y_compare.iloc[train_compare_idx]
y_test_compare = y_compare.iloc[test_compare_idx]

train_compare_domains = set(
    groups_compare.iloc[train_compare_idx]
)
test_compare_domains = set(
    groups_compare.iloc[test_compare_idx]
)

print("Training URLs:", len(X_train_compare))
print("Testing URLs:", len(X_test_compare))
print("Overlapping registered domains:",
      len(train_compare_domains & test_compare_domains))
print("Number of features:", X_train_compare.shape[1])
print("Features:", android_features)

Training URLs: 104937
Testing URLs: 26230
Overlapping registered domains: 0
Number of features: 8
Features: ['url_length', 'dot_count', 'hyphen_count', 'is_https', 'at_count', 'digit_count', 'slash_count', 'has_ip']

In [ ]:

# STEP 26.2: Train and evaluate three candidate models
# This does not replace or export the final Android model.

import pandas as pd

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# 1. Define the candidate models.
comparison_models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(),
        LogisticRegression(
            class_weight="balanced",
            max_iter=1000,
            random_state=42
        )
    ),

    "Decision Tree": DecisionTreeClassifier(
        max_depth=10,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )
}

# 2. Train and evaluate each model on the same split.
comparison_results = []
comparison_confusion_matrices = {}

for model_name, model in comparison_models.items():
    print(f"Training {model_name}...")

    model.fit(X_train_compare, y_train_compare)

    # Probability of class 1.
    # This assumes label 1 means phishing.
    phishing_class_index = list(model.classes_).index(1)
    phishing_probabilities = model.predict_proba(
        X_test_compare
    )[:, phishing_class_index]

    # Use the same 0.30 threshold for all models.
    predictions = (
        phishing_probabilities >= 0.30
    ).astype(int)

    comparison_results.append({
        "Model": model_name,
        "Accuracy": accuracy_score(
            y_test_compare, predictions
        ),
        "Precision": precision_score(
            y_test_compare, predictions,
            zero_division=0
        ),
        "Recall": recall_score(
            y_test_compare, predictions,
            zero_division=0
        ),
        "F1-score": f1_score(
            y_test_compare, predictions,
            zero_division=0
        )
    })

    comparison_confusion_matrices[model_name] = (
        confusion_matrix(
            y_test_compare,
            predictions,
            labels=[0, 1]
        )
    )

# 3. Display the comparison.
comparison_table = pd.DataFrame(comparison_results)

metric_columns = [
    "Accuracy", "Precision", "Recall", "F1-score"
]

comparison_table[metric_columns] = (
    comparison_table[metric_columns].round(4)
)

print("\nMODEL COMPARISON (threshold = 0.30)")
display(comparison_table)

# 4. Show confusion matrices.
for model_name, matrix in comparison_confusion_matrices.items():
    print(f"\n{model_name} confusion matrix")
    print("Rows = actual [legitimate, phishing]")
    print("Columns = predicted [legitimate, phishing]")
    print(matrix)

Training Logistic Regression...
Training Decision Tree...
Training Random Forest...

MODEL COMPARISON (threshold = 0.30)

                 Model  Accuracy  Precision  Recall  F1-score
0  Logistic Regression    0.9322     0.9209  0.9881    0.9533
1        Decision Tree    0.9360     0.9266  0.9867    0.9557
2        Random Forest    0.9365     0.9264  0.9878    0.9561

Logistic Regression confusion matrix
Rows = actual [legitimate, phishing]
Columns = predicted [legitimate, phishing]
[[ 6300  1559]
 [  219 18152]]

Decision Tree confusion matrix
Rows = actual [legitimate, phishing]
Columns = predicted [legitimate, phishing]
[[ 6424  1435]
 [  245 18126]]

Random Forest confusion matrix
Rows = actual [legitimate, phishing]
Columns = predicted [legitimate, phishing]
[[ 6417  1442]
 [  224 18147]]

In [ ]:
# STEP 26.3: Save the model comparison results

comparison_table.to_csv(
    "tinyphish_model_comparison.csv",
    index=False
)

print("Saved: tinyphish_model_comparison.csv")
print("\nComparison results:")
display(comparison_table)

Saved: tinyphish_model_comparison.csv

Comparison results:

                 Model  Accuracy  Precision  Recall  F1-score
0  Logistic Regression    0.9322     0.9209  0.9881    0.9533
1        Decision Tree    0.9360     0.9266  0.9867    0.9557
2        Random Forest    0.9365     0.9264  0.9878    0.9561

In [ ]:
# STEP 27: Inspect the registered-domain model's feature importance

importance_domain = pd.DataFrame({
    "Feature": X_train_d.columns,
    "Importance": registered_domain_model.feature_importances_
}).sort_values(
    by="Importance",
    ascending=False
)

print("Top 15 features:")
display(importance_domain.head(15).round(5))

print("\nHTTPS feature importance:")
display(
    importance_domain[
        importance_domain["Feature"] == "is_https"
    ].round(5)
)

print("\nBangladesh-related features:")
display(
    importance_domain[
        importance_domain["Feature"].str.contains(
            "bd_brand|bd_gov|brand|typosquatting|new_tld_is_bd",
            case=False,
            regex=True
        )
    ].round(5)
)

Top 15 features:

                   Feature  Importance
40                is_https     0.65876
0               url_length     0.17260
8              slash_count     0.04737
55             is_free_tld     0.02418
32        tld_count_in_url     0.01743
20             digit_ratio     0.01579
25   longest_consonant_run     0.01122
19              tld_length     0.01053
2         subdomain_length     0.00643
23          entropy_domain     0.00441
21            letter_ratio     0.00413
35  new_domain_vowel_ratio     0.00368
16         subdomain_count     0.00315
28        max_token_length     0.00302
46    has_suspicious_words     0.00280

HTTPS feature importance:

     Feature  Importance
40  is_https     0.65876

Bangladesh-related features:

                        Feature  Importance
30      min_brand_edit_distance     0.00153
58             is_typosquatting     0.00078
51              bd_brand_in_url     0.00004
54               bd_gov_keyword     0.00000
53  bd_brand_in_path_not_domain     0.00000
52   bd_brand_in_sub_not_domain     0.00000
57            bd_brand_free_tld     0.00000
66                new_tld_is_bd     0.00000
67           new_brand_in_query     0.00000

In [ ]:
# STEP 28: Registered-domain model without HTTPS

X_train_d_no_https = X_train_d.drop(
    columns=["is_https"]
)

X_test_d_no_https = X_test_d.drop(
    columns=["is_https"]
)

model_domain_no_https = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

model_domain_no_https.fit(
    X_train_d_no_https,
    y_train_d
)

pred_domain_no_https = model_domain_no_https.predict(
    X_test_d_no_https
)

print("Accuracy:", round(
    accuracy_score(y_test_d, pred_domain_no_https), 4
))
print("Precision:", round(
    precision_score(y_test_d, pred_domain_no_https, zero_division=0), 4
))
print("Recall:", round(
    recall_score(y_test_d, pred_domain_no_https, zero_division=0), 4
))
print("F1-score:", round(
    f1_score(y_test_d, pred_domain_no_https, zero_division=0), 4
))

print("\nConfusion matrix:")
print(confusion_matrix(y_test_d, pred_domain_no_https))

Accuracy: 0.848
Precision: 0.9743
Recall: 0.8041
F1-score: 0.8811

Confusion matrix:
[[ 7470   389]
 [ 3599 14772]]

In [ ]:
# STEP 31: Check whether the is_https feature matches the raw URL

import pandas as pd

url_scheme = phishbd_df["url"].astype(str).str.lower().str.match(
    r"^https://"
)

print("Raw URL starts with https://:")
print(pd.crosstab(
    phishbd_df["label"],
    url_scheme,
    rownames=["label"],
    colnames=["Raw URL uses HTTPS"]
))

print("\nStored is_https feature:")
print(pd.crosstab(
    phishbd_df["label"],
    phishbd_df["is_https"],
    rownames=["label"],
    colnames=["is_https feature"]
))

print("\nRows where raw URL scheme disagrees with is_https:")
mismatch = url_scheme.astype(int) != phishbd_df["is_https"].astype(int)
print("Mismatch count:", mismatch.sum())
print("Mismatch percentage:", round(mismatch.mean() * 100, 4), "%")

display(
    phishbd_df.loc[mismatch, ["url", "label", "is_https"]].head(10)
)

Raw URL starts with https://:
Raw URL uses HTTPS  False  True
label
0                   10000  29350
1                   89440   2377

Stored is_https feature:
is_https feature      0      1
label
0                 10000  29350
1                 89440   2377

Rows where raw URL scheme disagrees with is_https:
Mismatch count: 0
Mismatch percentage: 0.0 %

Empty DataFrame
Columns: [url, label, is_https]
Index: []

In [ ]:
# STEP 32: Fair comparison of the two models

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)
import pandas as pd

# 1. Verify that both models use exactly the same test rows
same_rows = (
    X_test.index.equals(X_test_no_cv_domain.index)
    and y_test.index.equals(y_test_cv.index)
)

print("Same test URLs:", same_rows)

if not same_rows:
    print(
        "STOP: The test rows differ. "
        "We must align the test sets before comparing."
    )
else:
    # 2. Generate predictions on the shared test URLs
    old_predictions = model_bd_baseline.predict(X_test)

    new_predictions = model_no_cv_domain.predict(
        X_test_no_cv_domain
    )

    # 3. Calculate the evaluation metrics
    results = []

    for name, actual, predicted in [
        ("Original 8-feature model", y_test, old_predictions),
        ("Experimental 71-feature model", y_test_cv, new_predictions)
    ]:
        results.append({
            "Model": name,
            "Accuracy": accuracy_score(actual, predicted),
            "Precision": precision_score(
                actual, predicted, zero_division=0
            ),
            "Recall": recall_score(
                actual, predicted, zero_division=0
            ),
            "F1-score": f1_score(
                actual, predicted, zero_division=0
            )
        })

    comparison = pd.DataFrame(results)

    print("\nComparison on the same test URLs:")
    display(
        comparison.set_index("Model").round(4)
    )

    print("\nOriginal model confusion matrix:")
    print(confusion_matrix(y_test, old_predictions))

    print("\nExperimental model confusion matrix:")
    print(confusion_matrix(y_test_cv, new_predictions))

Same test URLs: True

Comparison on the same test URLs:

                               Accuracy  Precision  Recall  F1-score
Model
Original 8-feature model         0.9238     0.9579  0.9322    0.9449
Experimental 71-feature model    0.9433     0.9684  0.9501    0.9591

Original model confusion matrix:
[[ 7117   753]
 [ 1245 17119]]

Experimental model confusion matrix:
[[ 7300   570]
 [  917 17447]]

In [ ]:
# STEP 32: Fair comparison of the two models

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)
import pandas as pd

# 1. Verify that both models use exactly the same test rows
same_rows = (
    X_test.index.equals(X_test_no_cv_domain.index)
    and y_test.index.equals(y_test_cv.index)
)

print("Same test URLs:", same_rows)

if not same_rows:
    print(
        "STOP: The test rows differ. "
        "We must align the test sets before comparing."
    )
else:
    # 2. Generate predictions on the shared test URLs
    old_predictions = model_bd_baseline.predict(X_test)

    new_predictions = model_no_cv_domain.predict(
        X_test_no_cv_domain
    )

    # 3. Calculate the evaluation metrics
    results = []

    for name, actual, predicted in [
        ("Original 8-feature model", y_test, old_predictions),
        ("Experimental 71-feature model", y_test_cv, new_predictions)
    ]:
        results.append({
            "Model": name,
            "Accuracy": accuracy_score(actual, predicted),
            "Precision": precision_score(
                actual, predicted, zero_division=0
            ),
            "Recall": recall_score(
                actual, predicted, zero_division=0
            ),
            "F1-score": f1_score(
                actual, predicted, zero_division=0
            )
        })

    comparison = pd.DataFrame(results)

    print("\nComparison on the same test URLs:")
    display(
        comparison.set_index("Model").round(4)
    )

    print("\nOriginal model confusion matrix:")
    print(confusion_matrix(y_test, old_predictions))

    print("\nExperimental model confusion matrix:")
    print(confusion_matrix(y_test_cv, new_predictions))

Same test URLs: True

Comparison on the same test URLs:

                               Accuracy  Precision  Recall  F1-score
Model
Original 8-feature model         0.9238     0.9579  0.9322    0.9449
Experimental 71-feature model    0.9433     0.9684  0.9501    0.9591

Original model confusion matrix:
[[ 7117   753]
 [ 1245 17119]]

Experimental model confusion matrix:
[[ 7300   570]
 [  917 17447]]

In [ ]:
import os

for filename in [
    "phishing_tree.json",
    "phishing_tree_threshold03_android.json",
    "phishing_tree_depth12.json",
    "tinyphish_phishbd_experiment.joblib"
]:
    if os.path.exists(filename):
        size = os.path.getsize(filename)
        print(f"{filename}: {size:,} bytes ({size / 1024:.2f} KB)")
    else:
        print(f"{filename}: Not found in the current folder")

phishing_tree.json: 118,002 bytes (115.24 KB)
phishing_tree_threshold03_android.json: 79,450 bytes (77.59 KB)
phishing_tree_depth12.json: 75,427 bytes (73.66 KB)
tinyphish_phishbd_experiment.joblib: 43,753 bytes (42.73 KB)

In [ ]:
import hashlib

filename = "/content/phishing_tree_threshold03_android.json"

with open(filename, "rb") as f:
    sha256_hash = hashlib.sha256(f.read()).hexdigest()

print("File:", filename)
print("SHA-256:", sha256_hash)

File: /content/phishing_tree_threshold03_android.json
SHA-256: c4cced42710b954bf1cfa273e3241a2832cbbd35b9afdf5eee8762c7de3e0617

In [ ]:

# STEP 34: Compare mistakes made by both models

comparison_errors = pd.DataFrame({
    "url": phishbd_df.loc[y_test_cv.index, "url"],
    "Actual": y_test_cv,
    "Original_prediction": old_predictions,
    "Experimental_prediction": new_predictions
}, index=y_test_cv.index)

# Mistakes fixed by the experimental model
fixed_errors = comparison_errors[
    (comparison_errors["Actual"] != comparison_errors["Original_prediction"]) &
    (comparison_errors["Actual"] == comparison_errors["Experimental_prediction"])
]

# Mistakes newly introduced by the experimental model
new_errors = comparison_errors[
    (comparison_errors["Actual"] == comparison_errors["Original_prediction"]) &
    (comparison_errors["Actual"] != comparison_errors["Experimental_prediction"])
]

# Phishing URLs missed by the experimental model
missed_phishing = comparison_errors[
    (comparison_errors["Actual"] == 1) &
    (comparison_errors["Experimental_prediction"] == 0)
]

# Legitimate URLs incorrectly flagged by the experimental model
false_alarms = comparison_errors[
    (comparison_errors["Actual"] == 0) &
    (comparison_errors["Experimental_prediction"] == 1)
]

print("Original mistakes corrected by experimental model:", len(fixed_errors))
display(fixed_errors.head(10))

print("\nPreviously correct predictions made wrong:", len(new_errors))
display(new_errors.head(10))

print("\nPhishing URLs missed by experimental model:")
display(missed_phishing.head(10))

print("\nLegitimate URLs incorrectly flagged by experimental model:")
display(false_alarms.head(10))

Original mistakes corrected by experimental model: 923

,url,Actual,Original_prediction,Experimental_prediction
36925,http://bignews.fun,1,0,1
130853,http://dereal.xyz,1,0,1
7740,http://b.orlens.pw,1,0,1
49156,http://optusnet.com.au,0,1,0
84452,http://gritless.sbs,1,0,1
4662,http://prokes.life,1,0,1
32652,http://auth0edge.com,0,1,0
13631,http://lyhlsmou.cc,1,0,1
100576,http://flkfeg.top,1,0,1
56831,http://eroytid.site,1,0,1

Previously correct predictions made wrong: 412

,url,Actual,Original_prediction,Experimental_prediction
124272,http://hm.ru/2mGhJ2,1,1,0
5791,http://hitza-hitz.com,1,1,0
1463,http://saasclash.com,1,1,0
39481,http://dicosis-sys.com,1,1,0
67943,http://xzvsadt7.com,1,1,0
21146,http://emartcafe.com,1,1,0
77565,http://plastisun.com,1,1,0
82687,http://timonshop.com,1,1,0
67347,http://ketogo.app,0,0,1
27096,http://pl-poczta.net,1,1,0

Phishing URLs missed by experimental model:

,url,Actual,Original_prediction,Experimental_prediction
124272,http://hm.ru/2mGhJ2,1,1,0
71281,http://coinnmf.com,1,0,0
1836,http://enzidev.com,1,0,0
117909,http://rodprada.com,1,0,0
90187,http://menducos.com,1,0,0
5791,http://hitza-hitz.com,1,1,0
36958,http://yutucoin.com,1,0,0
1463,http://saasclash.com,1,1,0
39481,http://dicosis-sys.com,1,1,0
67943,http://xzvsadt7.com,1,1,0

Legitimate URLs incorrectly flagged by experimental model:

,url,Actual,Original_prediction,Experimental_prediction
91034,http://stumbleupon.com,0,1,1
15564,http://oxfordjournals.org,0,1,1
127842,http://theglobeandmail.com,0,1,1
38236,http://xhpingcdn.com,0,1,1
67347,http://ketogo.app,0,0,1
96500,http://truyenqqno.com,0,1,1
90669,http://springeropen.com,0,1,1
84073,http://name-services.com,0,1,1
22020,http://gammaplatform.com,0,1,1
51983,http://computrabajo.com,0,1,1

In [ ]:

# Check which models are available and compare their feature counts

print("Original export variable 'model':")
try:
    print("Number of input features:", model.n_features_in_)
    print("Model depth:", model.get_depth())
    print("Number of leaves:", model.get_n_leaves())
except NameError:
    print("The variable 'model' does not exist.")

print("\nPhishBD baseline model 'model_bd_baseline':")
print("Number of input features:", model_bd_baseline.n_features_in_)
print("Model depth:", model_bd_baseline.get_depth())
print("Number of leaves:", model_bd_baseline.get_n_leaves())

Original export variable 'model':
Number of input features: 8
Model depth: 12
Number of leaves: 739

PhishBD baseline model 'model_bd_baseline':
Number of input features: 8
Model depth: 10
Number of leaves: 324

In [ ]:

# STEP 37: Export a separate experimental model
# The existing Android model will NOT be overwritten.

import json
import os

experimental_tree = model_bd_baseline.tree_

experimental_model_data = {
    "children_left": experimental_tree.children_left.tolist(),
    "children_right": experimental_tree.children_right.tolist(),
    "features": experimental_tree.feature.tolist(),
    "thresholds": experimental_tree.threshold.tolist(),
    "values": experimental_tree.value.squeeze(axis=1).tolist()
}

experimental_filename = "/content/phishbd_baseline_experimental.json"

with open(experimental_filename, "w") as f:
    json.dump(experimental_model_data, f)

print("Export completed.")
print("Filename:", experimental_filename)
print("Size:", round(os.path.getsize(experimental_filename) / 1024, 2), "KB")
print("Input features:", model_bd_baseline.n_features_in_)
print("Tree depth:", model_bd_baseline.get_depth())
print("Leaves:", model_bd_baseline.get_n_leaves())
print("JSON keys:", list(experimental_model_data.keys()))

Export completed.
Filename: /content/phishbd_baseline_experimental.json
Size: 33.04 KB
Input features: 8
Tree depth: 10
Leaves: 324
JSON keys: ['children_left', 'children_right', 'features', 'thresholds', 'values']

In [ ]:

# STEP 38: Inspect the experimental tree's leaf values

import json
import numpy as np

filename = "/content/phishbd_baseline_experimental.json"

with open(filename, "r") as f:
    experimental_data = json.load(f)

values = np.array(experimental_data["values"], dtype=float)
left = np.array(experimental_data["children_left"])
right = np.array(experimental_data["children_right"])

leaf_mask = (left == -1) & (right == -1)
leaf_values = values[leaf_mask]

print("Total nodes:", len(left))
print("Leaf nodes:", int(leaf_mask.sum()))
print("Example leaf values:")
print(leaf_values[:10])

print("\nExample leaf class probabilities:")
totals = leaf_values.sum(axis=1)
probabilities = np.divide(
    leaf_values[:, 1],
    totals,
    out=np.zeros_like(totals),
    where=totals != 0
)
print(np.round(probabilities[:10], 4))

print("\nClass values stored in a leaf:")
print("Minimum:", leaf_values.min())
print("Maximum:", leaf_values.max())

Total nodes: 647
Leaf nodes: 324
Example leaf values:
[[1.         0.        ]
 [0.98585344 0.01414656]
 [0.89414618 0.10585382]
 [1.         0.        ]
 [0.         1.        ]
 [1.         0.        ]
 [0.         1.        ]
 [0.53846041 0.46153959]
 [0.77283909 0.22716091]
 [0.74172098 0.25827902]]

Example leaf class probabilities:
[0.     0.0141 0.1059 0.     1.     0.     1.     0.4615 0.2272 0.2583]

Class values stored in a leaf:
Minimum: 0.0
Maximum: 1.0

In [ ]:

# STEP 39: Evaluate the experimental model at threshold 0.30

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Get the model's phishing probabilities (class 1)
phishing_probabilities = model_bd_baseline.predict_proba(X_test)[:, 1]

# Match the threshold currently used by Android
predictions_030 = (phishing_probabilities >= 0.30).astype(int)

print("Experimental 8-feature model")
print("Threshold: 0.30")
print("Accuracy:", round(accuracy_score(y_test, predictions_030), 4))
print("Precision:", round(precision_score(y_test, predictions_030, zero_division=0), 4))
print("Recall:", round(recall_score(y_test, predictions_030, zero_division=0), 4))
print("F1-score:", round(f1_score(y_test, predictions_030, zero_division=0), 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, predictions_030, labels=[0, 1]))

Experimental 8-feature model
Threshold: 0.30
Accuracy: 0.9382
Precision: 0.9286
Recall: 0.9876
F1-score: 0.9572

Confusion matrix:
[[ 6475  1395]
 [  227 18137]]

In [ ]:

# STEP 40: Verify exported JSON tree predictions

import numpy as np

def predict_from_exported_tree(row, data, threshold=0.30):
    node = 0

    while data["children_left"][node] != -1:
        feature_index = data["features"][node]
        split_threshold = data["thresholds"][node]

        if row[feature_index] <= split_threshold:
            node = data["children_left"][node]
        else:
            node = data["children_right"][node]

    benign, phishing = data["values"][node]
    total = benign + phishing

    probability = phishing / total if total > 0 else 0.0
    return int(probability >= threshold), probability

# Use the same test rows and threshold as before.
test_rows = X_test.iloc[:20].to_numpy(dtype=float)
sklearn_probabilities = model_bd_baseline.predict_proba(
    X_test.iloc[:20]
)[:, 1]

export_predictions = []
export_probabilities = []

for row in test_rows:
    prediction, probability = predict_from_exported_tree(
        row, experimental_model_data, threshold=0.30
    )
    export_predictions.append(prediction)
    export_probabilities.append(probability)

print("Scikit-learn probabilities:")
print(np.round(sklearn_probabilities, 6))

print("\nExported JSON probabilities:")
print(np.round(export_probabilities, 6))

print("\nPredictions match:",
      np.array_equal(
          (sklearn_probabilities >= 0.30).astype(int),
          np.array(export_predictions)
      ))

print("Maximum probability difference:",
      round(float(np.max(np.abs(
          sklearn_probabilities - np.array(export_probabilities)
      ))), 10))

Scikit-learn probabilities:
[8.90226e-01 1.00000e-03 1.00000e-03 1.00000e+00 8.40120e-01 1.00000e+00
 1.00000e+00 1.00000e+00 1.00000e-03 1.00000e+00 1.00000e+00 8.46089e-01
 1.00000e-03 1.00000e+00 8.52048e-01 9.10970e-01 1.64000e-04 1.00000e-03
 3.78231e-01 1.00000e-03]

Exported JSON probabilities:
[8.90226e-01 1.00000e-03 1.00000e-03 1.00000e+00 8.40120e-01 1.00000e+00
 1.00000e+00 1.00000e+00 1.00000e-03 1.00000e+00 1.00000e+00 8.46089e-01
 1.00000e-03 1.00000e+00 8.52048e-01 9.10970e-01 1.64000e-04 1.00000e-03
 3.78231e-01 1.00000e-03]

Predictions match: True
Maximum probability difference: 0.0

In [ ]:

# STEP 41: Verify exported tree on the entire test set

import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

sklearn_probs = model_bd_baseline.predict_proba(X_test)[:, 1]
json_probs = np.array([
    predict_from_exported_tree(
        row, experimental_model_data, threshold=0.30
    )[1]
    for row in X_test.to_numpy(dtype=float)
])

sklearn_preds = (sklearn_probs >= 0.30).astype(int)
json_preds = (json_probs >= 0.30).astype(int)

print("Total test samples:", len(X_test))
print("Probability arrays match:", np.allclose(sklearn_probs, json_probs))
print("Predictions match:", np.array_equal(sklearn_preds, json_preds))
print("Maximum probability difference:",
      float(np.max(np.abs(sklearn_probs - json_probs))))

print("\nExported JSON metrics")
print("Accuracy:", round(accuracy_score(y_test, json_preds), 4))
print("Precision:", round(precision_score(y_test, json_preds, zero_division=0), 4))
print("Recall:", round(recall_score(y_test, json_preds, zero_division=0), 4))
print("F1-score:", round(f1_score(y_test, json_preds, zero_division=0), 4))

Total test samples: 26234
Probability arrays match: True
Predictions match: True
Maximum probability difference: 7.882583474838611e-15

Exported JSON metrics
Accuracy: 0.9382
Precision: 0.9286
Recall: 0.9876
F1-score: 0.9572

In [ ]:

# STEP 42: Record experimental model details

import os

tree = model_bd_baseline.tree_
model_path = "/content/phishbd_baseline_experimental.json"

print("Model file exists:", os.path.exists(model_path))
print("Model size (KB):", round(os.path.getsize(model_path) / 1024, 2))
print("Number of input features:", model_bd_baseline.n_features_in_)
print("Tree depth:", tree.max_depth)
print("Total nodes:", tree.node_count)
print("Leaf nodes:", sum(tree.children_left == -1))
print("Internal nodes:", sum(tree.children_left != -1))
print("Classification threshold: 0.30")

Model file exists: True
Model size (KB): 33.04
Number of input features: 8
Tree depth: 10
Total nodes: 647
Leaf nodes: 324
Internal nodes: 323
Classification threshold: 0.30

In [ ]:

# STEP 43: Inspect the current Android model

print("Current model variable exists:", "model" in globals())

if "model" in globals():
    current_tree = model.tree_

    print("Current model features:", model.n_features_in_)
    print("Current model depth:", current_tree.max_depth)
    print("Current model nodes:", current_tree.node_count)
    print("Current model leaves:",
          sum(current_tree.children_left == -1))
else:
    print("The original model variable is not available in this notebook.")

Current model variable exists: True
Current model features: 8
Current model depth: 12
Current model nodes: 1477
Current model leaves: 739

In [ ]:

# STEP 44: Compare both models on exactly the same test set

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix
)
import pandas as pd

# The current model uses the same eight feature columns.
current_probabilities = model.predict_proba(X_test)[:, 1]
current_predictions = (current_probabilities >= 0.30).astype(int)

experimental_probabilities = model_bd_baseline.predict_proba(X_test)[:, 1]
experimental_predictions = (
    experimental_probabilities >= 0.30
).astype(int)

def show_metrics(name, actual, predicted):
    print(f"\n{name}")
    print("Accuracy:", round(accuracy_score(actual, predicted), 4))
    print("Precision:", round(precision_score(actual, predicted, zero_division=0), 4))
    print("Recall:", round(recall_score(actual, predicted, zero_division=0), 4))
    print("F1-score:", round(f1_score(actual, predicted, zero_division=0), 4))
    print("Confusion matrix:")
    print(confusion_matrix(actual, predicted, labels=[0, 1]))

show_metrics("Current depth-12 model", y_test, current_predictions)
show_metrics("Experimental depth-10 model", y_test, experimental_predictions)

Current depth-12 model
Accuracy: 0.5719
Precision: 0.9071
Recall: 0.4327
F1-score: 0.5859
Confusion matrix:
[[ 7056   814]
 [10418  7946]]

Experimental depth-10 model
Accuracy: 0.9382
Precision: 0.9286
Recall: 0.9876
F1-score: 0.9572
Confusion matrix:
[[ 6475  1395]
 [  227 18137]]

In [ ]:

# STEP 45: Inspect the dataset's eight features

feature_columns = [
    "url_length",
    "dot_count",
    "hyphen_count",
    "is_https",
    "at_count",
    "digit_count",
    "slash_count",
    "has_ip"
]

print("Feature columns:")
for i, column in enumerate(feature_columns):
    print(f"{i}: {column}")

print("\nSample URLs and feature values:")
display(
    phishbd_df[["url"] + feature_columns].head(10)
)

print("\nData types:")
print(phishbd_df[feature_columns].dtypes)

print("\nMissing values:")
print(phishbd_df[feature_columns].isna().sum())

Feature columns:
0: url_length
1: dot_count
2: hyphen_count
3: is_https
4: at_count
5: digit_count
6: slash_count
7: has_ip

Sample URLs and feature values:

,url,url_length,dot_count,hyphen_count,is_https,at_count,digit_count,slash_count,has_ip
0,http://www.au-payccoy.aseacaameoy.tvxp.top/AU/...,55.0,5.0,1.0,0,0.0,1.0,4.0,0
1,http://hkpgk.the-drone-company.com,34.0,2.0,2.0,0,0.0,0.0,2.0,0
2,http://marconishop.com,22.0,1.0,0.0,0,0.0,0.0,2.0,0
3,http://stage-coingeb.com,24.0,1.0,1.0,0,0.0,0.0,2.0,0
4,http://xgiqfrqcebklsdsyy.click,30.0,1.0,0.0,0,0.0,0.0,2.0,0
5,http://faywho.com,17.0,1.0,0.0,0,0.0,0.0,2.0,0
6,http://customeremailsupport.com,31.0,1.0,0.0,0,0.0,0.0,2.0,0
7,http://www.pauleames.com,24.0,2.0,0.0,0,0.0,0.0,2.0,0
8,http://xqpxkkx.cn,17.0,1.0,0.0,0,0.0,0.0,2.0,0
9,http://bimcellcumartesii.com,28.0,1.0,0.0,0,0.0,0.0,2.0,0

Data types:
url_length      float64
dot_count       float64
hyphen_count    float64
is_https          int64
at_count        float64
digit_count     float64
slash_count     float64
has_ip            int64
dtype: object

Missing values:
url_length      0
dot_count       0
hyphen_count    0
is_https        0
at_count        0
digit_count     0
slash_count     0
has_ip          0
dtype: int64

In [ ]:

# STEP 46: Check feature extraction on representative URLs

from urllib.parse import urlparse
import ipaddress

test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login",
    "http://192.168.1.1/login@verify",
    "example.com/path",
    "HTTPS://Example.com/path",
    "http://[2001:db8::1]/login"
]

def android_style_features(url):
    lower = url.lower()
    normalized = url if "://" in url else "http://" + url

    try:
        host = urlparse(normalized).hostname or ""
        try:
            ipaddress.ip_address(host)
            has_ip = 1
        except ValueError:
            has_ip = 0
    except Exception:
        has_ip = 0

    return [
        len(url),
        url.count("."),
        url.count("-"),
        int(lower.startswith("https://")),
        int("@" in url),
        sum(ch.isdigit() for ch in url),
        url.count("/"),
        has_ip
    ]

for url in test_urls:
    print("\nURL:", url)
    print("Python features:", android_style_features(url))

URL: https://www.google.com
Python features: [22, 2, 0, 1, 0, 0, 2, 0]

URL: http://192.168.1.1/login
Python features: [24, 3, 0, 0, 0, 8, 3, 1]

URL: http://192.168.1.1/login@verify
Python features: [31, 3, 0, 0, 1, 8, 3, 1]

URL: example.com/path
Python features: [16, 1, 0, 0, 0, 0, 1, 0]

URL: HTTPS://Example.com/path
Python features: [24, 1, 0, 1, 0, 0, 3, 0]

URL: http://[2001:db8::1]/login
Python features: [26, 0, 0, 0, 0, 6, 3, 1]

In [ ]:

# STEP 47: Test familiar URLs with the experimental model

import pandas as pd

test_urls = [
    "https://www.google.com",
    "https://www.facebook.com",
    "https://www.youtube.com",
    "http://192.168.1.1/login",
    "http://192.168.1.1/login@verify",
    "https://example.com/login",
    "http://example.com/verify-account",
    "http://secure-login-example.com/account"
]

def make_eight_features(url):
    lower = url.lower()

    from urllib.parse import urlparse
    import ipaddress

    normalized = url if "://" in url else "http://" + url

    try:
        host = urlparse(normalized).hostname or ""
        try:
            ipaddress.ip_address(host)
            has_ip = 1
        except ValueError:
            has_ip = 0
    except Exception:
        has_ip = 0

    return [
        len(url),
        url.count("."),
        url.count("-"),
        int(lower.startswith("https://")),
        int("@" in url),
        sum(ch.isdigit() for ch in url),
        url.count("/"),
        has_ip
    ]

test_features = pd.DataFrame(
    [make_eight_features(url) for url in test_urls],
    columns=X_test.columns
)

probabilities = model_bd_baseline.predict_proba(test_features)[:, 1]
predictions = (probabilities >= 0.30).astype(int)

results = pd.DataFrame({
    "URL": test_urls,
    "Phishing probability": probabilities.round(4),
    "Prediction": [
        "Phishing" if p == 1 else "Legitimate"
        for p in predictions
    ]
})

display(results)

                                       URL  Phishing probability  Prediction
0                   https://www.google.com                0.0049  Legitimate
1                 https://www.facebook.com                0.0049  Legitimate
2                  https://www.youtube.com                0.0049  Legitimate
3                 http://192.168.1.1/login                1.0000    Phishing
4          http://192.168.1.1/login@verify                1.0000    Phishing
5                https://example.com/login                1.0000    Phishing
6        http://example.com/verify-account                1.0000    Phishing
7  http://secure-login-example.com/account                0.9468    Phishing

In [ ]:

# STEP 48: Compare two classification thresholds

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix
)

probabilities = model_bd_baseline.predict_proba(X_test)[:, 1]

for threshold in [0.30, 0.50]:
    predictions = (probabilities >= threshold).astype(int)

    print(f"\nThreshold: {threshold:.2f}")
    print("Accuracy:", round(accuracy_score(y_test, predictions), 4))
    print("Precision:", round(precision_score(y_test, predictions, zero_division=0), 4))
    print("Recall:", round(recall_score(y_test, predictions, zero_division=0), 4))
    print("F1-score:", round(f1_score(y_test, predictions, zero_division=0), 4))
    print("Confusion matrix:")
    print(confusion_matrix(y_test, predictions, labels=[0, 1]))

Threshold: 0.30
Accuracy: 0.9382
Precision: 0.9286
Recall: 0.9876
F1-score: 0.9572
Confusion matrix:
[[ 6475  1395]
 [  227 18137]]

Threshold: 0.50
Accuracy: 0.9238
Precision: 0.9579
Recall: 0.9322
F1-score: 0.9449
Confusion matrix:
[[ 7117   753]
 [ 1245 17119]]

In [ ]:

# STEP 49: Compare candidate thresholds

import pandas as pd
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix
)

probabilities = model_bd_baseline.predict_proba(X_test)[:, 1]
thresholds_to_test = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]

rows = []

for threshold in thresholds_to_test:
    predictions = (probabilities >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(
        y_test, predictions, labels=[0, 1]
    ).ravel()

    rows.append({
        "Threshold": threshold,
        "Accuracy": round(accuracy_score(y_test, predictions), 4),
        "Precision": round(precision_score(y_test, predictions, zero_division=0), 4),
        "Recall": round(recall_score(y_test, predictions, zero_division=0), 4),
        "F1-score": round(f1_score(y_test, predictions, zero_division=0), 4),
        "False positives": fp,
        "Missed phishing": fn
    })

display(pd.DataFrame(rows))

,Threshold,Accuracy,Precision,Recall,F1-score,False positives,Missed phishing
0,0.20,0.9347,0.9189,0.9944,0.9552,1612,102
1,0.25,0.9380,0.9281,0.9879,0.9571,1405,222
2,0.30,0.9382,0.9286,0.9876,0.9572,1395,227
3,0.35,0.9362,0.9383,0.9728,0.9552,1174,500
4,0.40,0.9321,0.9472,0.9564,0.9518,980,800
5,0.45,0.9320,0.9477,0.9556,0.9516,969,815
6,0.50,0.9238,0.9579,0.9322,0.9449,753,1245

In [ ]:

# STEP CW1: Compare class weights for the experimental model

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix
)

# Keep the final test set separate during this experiment.
X_fit, X_val, y_fit, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

# Class 0 = legitimate; class 1 = phishing.
weight_options = [
    ("Equal (1:1)", {0: 1, 1: 1}),
    ("Phishing 1.5x", {0: 1, 1: 1.5}),
    ("Phishing 2x", {0: 1, 1: 2}),
    ("Phishing 3x", {0: 1, 1: 3}),
    ("Phishing 4x", {0: 1, 1: 4}),
    ("Phishing 5x", {0: 1, 1: 5}),
    ("Balanced", "balanced")
]

results = []

for name, class_weights in weight_options:
    candidate = DecisionTreeClassifier(
        max_depth=10,
        class_weight=class_weights,
        random_state=42
    )

    candidate.fit(X_fit, y_fit)

    # Evaluate phishing probability at the existing 0.30 threshold.
    probabilities = candidate.predict_proba(X_val)[:, 1]
    predictions = (probabilities >= 0.30).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        y_val, predictions, labels=[0, 1]
    ).ravel()

    results.append({
        "Class weight": name,
        "Accuracy": round(accuracy_score(y_val, predictions), 4),
        "Precision": round(precision_score(
            y_val, predictions, zero_division=0
        ), 4),
        "Recall": round(recall_score(
            y_val, predictions, zero_division=0
        ), 4),
        "F1-score": round(f1_score(
            y_val, predictions, zero_division=0
        ), 4),
        "False positives": int(fp),
        "Missed phishing": int(fn)
    })

results_df = pd.DataFrame(results)
display(results_df.sort_values("F1-score", ascending=False))

,Class weight,Accuracy,Precision,Recall,F1-score,False positives,Missed phishing
6,Balanced,0.9383,0.9290,0.9874,0.9573,1109,185
0,Equal (1:1),0.9360,0.9197,0.9954,0.9561,1277,67
1,Phishing 1.5x,0.9347,0.9176,0.9962,0.9553,1315,56
2,Phishing 2x,0.9315,0.9125,0.9979,0.9533,1406,31
3,Phishing 3x,0.9298,0.9099,0.9986,0.9522,1453,21
4,Phishing 4x,0.9298,0.9099,0.9986,0.9522,1453,21
5,Phishing 5x,0.9291,0.9092,0.9985,0.9518,1465,22

In [ ]:

# STEP CW2: Tune threshold for balanced vs equal class weights

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    precision_score, recall_score, f1_score, confusion_matrix
)

weight_candidates = [
    ("Balanced", "balanced"),
    ("Equal (1:1)", {0: 1, 1: 1})
]

threshold_candidates = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
rows = []

for weight_name, weights in weight_candidates:
    candidate = DecisionTreeClassifier(
        max_depth=10,
        class_weight=weights,
        random_state=42
    )
    candidate.fit(X_fit, y_fit)
    probabilities = candidate.predict_proba(X_val)[:, 1]

    for threshold in threshold_candidates:
        predictions = (probabilities >= threshold).astype(int)
        tn, fp, fn, tp = confusion_matrix(
            y_val, predictions, labels=[0, 1]
        ).ravel()

        rows.append({
            "Class weight": weight_name,
            "Threshold": threshold,
            "Precision": round(precision_score(
                y_val, predictions, zero_division=0
            ), 4),
            "Recall": round(recall_score(
                y_val, predictions, zero_division=0
            ), 4),
            "F1-score": round(f1_score(
                y_val, predictions, zero_division=0
            ), 4),
            "False positives": int(fp),
            "Missed phishing": int(fn)
        })

display(
    pd.DataFrame(rows).sort_values(
        ["F1-score", "Recall"], ascending=False
    ).reset_index(drop=True)
)

,Class weight,Threshold,Precision,Recall,F1-score,False positives,Missed phishing
0,Equal (1:1),0.50,0.9288,0.9875,0.9573,1112,183
1,Balanced,0.30,0.9290,0.9874,0.9573,1109,185
2,Equal (1:1),0.45,0.9286,0.9877,0.9572,1116,181
3,Balanced,0.25,0.9287,0.9875,0.9572,1113,183
4,Equal (1:1),0.30,0.9197,0.9954,0.9561,1277,67
5,Equal (1:1),0.35,0.9198,0.9952,0.9561,1274,70
6,Equal (1:1),0.40,0.9206,0.9945,0.9561,1260,81
7,Balanced,0.20,0.9208,0.9944,0.9561,1257,83
8,Equal (1:1),0.25,0.9190,0.9958,0.9559,1290,61
9,Balanced,0.35,0.9379,0.9732,0.9552,946,394
10,Equal (1:1),0.20,0.9129,0.9978,0.9534,1399,33
11,Balanced,0.40,0.9469,0.9551,0.9510,787,659
12,Balanced,0.45,0.9469,0.9550,0.9509,787,661
13,Balanced,0.50,0.9554,0.9306,0.9428,638,1020

In [ ]:

# STEP CW3: Final evaluation on the untouched test set

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)
import numpy as np

# Combine training and validation data after selecting the settings
X_final_train = np.concatenate([X_fit, X_val])
y_final_train = np.concatenate([y_fit, y_val])

# Train the selected eight-feature model
final_model = DecisionTreeClassifier(
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

final_model.fit(X_final_train, y_final_train)

# Predict phishing probabilities on the untouched test set
test_probabilities = final_model.predict_proba(X_test)[:, 1]

# Apply the selected threshold
threshold = 0.30
y_test_pred = (test_probabilities >= threshold).astype(int)

# Calculate final performance
tn, fp, fn, tp = confusion_matrix(
    y_test, y_test_pred, labels=[0, 1]
).ravel()

print("FINAL TEST RESULTS")
print("------------------")
print(f"Threshold: {threshold}")
print(f"Accuracy:  {accuracy_score(y_test, y_test_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_test_pred, zero_division=0):.4f}")
print(f"Recall:    {recall_score(y_test, y_test_pred, zero_division=0):.4f}")
print(f"F1-score:  {f1_score(y_test, y_test_pred, zero_division=0):.4f}")
print(f"False positives: {fp}")
print(f"Missed phishing: {fn}")
print(f"True negatives: {tn}")
print(f"True positives: {tp}")

FINAL TEST RESULTS
------------------
Threshold: 0.3
Accuracy:  0.9382
Precision: 0.9286
Recall:    0.9876
F1-score:  0.9572
False positives: 1395
Missed phishing: 227
True negatives: 6475
True positives: 18137

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(

In [ ]:

# STEP CW4: Export the final CW3 model separately
# This does NOT overwrite the existing Android model.

import json
import os

# Use the exact model evaluated in CW3
export_tree = final_model.tree_

# Preserve the JSON structure used by the experimental export
final_model_data = {
    "children_left": export_tree.children_left.tolist(),
    "children_right": export_tree.children_right.tolist(),
    "features": export_tree.feature.tolist(),
    "thresholds": export_tree.threshold.tolist(),
    "values": export_tree.value.squeeze(axis=1).tolist()
}

# Save under a NEW filename
final_filename = "/content/phishing_tree_final_cw3.json"

with open(final_filename, "w") as f:
    json.dump(final_model_data, f)

# Verify the exported file
file_size_kb = os.path.getsize(final_filename) / 1024

print("FINAL MODEL EXPORT")
print("------------------")
print("Export completed.")
print("Filename:", final_filename)
print("Size:", round(file_size_kb, 2), "KB")
print("Input features:", final_model.n_features_in_)
print("Tree depth:", final_model.get_depth())
print("Leaves:", final_model.get_n_leaves())
print("Number of tree nodes:", export_tree.node_count)
print("JSON keys:", list(final_model_data.keys()))

assert final_model.n_features_in_ == 8, \
    "ERROR: Expected exactly 8 input features."

assert os.path.getsize(final_filename) < 1024 * 1024, \
    "ERROR: Exported model exceeds 1 MB."

print("Verification: PASS")

FINAL MODEL EXPORT
------------------
Export completed.
Filename: /content/phishing_tree_final_cw3.json
Size: 32.98 KB
Input features: 8
Tree depth: 10
Leaves: 323
Number of tree nodes: 645
JSON keys: ['children_left', 'children_right', 'features', 'thresholds', 'values']
Verification: PASS

In [ ]:

# STEP CW5: Download the final CW3 model

from google.colab import files

files.download("/content/phishing_tree_final_cw3.json")

In [ ]:
# Day 9 — Step 62: Check the final model's predictions

test_urls = [
    "https://www.google.com",
    "http://192.168.1.1/login@verify",
    "192.168.1.1/login",
    "HTTPS://Example.com/path",
    "https://example.com/path",
    "example.com/path",
    "https://[2001:db8::1]/login"
]

for url in test_urls:
    features = extract_features(url)  # Use your existing feature function
    probability = final_model.predict_proba([features])[0][1]
    prediction = "Phishing" if probability >= 0.30 else "Benign"

    print(
        f"URL: {url}\n"
        f"Phishing probability: {probability:.4f}\n"
        f"Prediction: {prediction}\n"
    )

URL: https://www.google.com
Phishing probability: 0.0049
Prediction: Benign

URL: http://192.168.1.1/login@verify
Phishing probability: 1.0000
Prediction: Phishing

URL: 192.168.1.1/login
Phishing probability: 1.0000
Prediction: Phishing

URL: HTTPS://Example.com/path
Phishing probability: 1.0000
Prediction: Phishing

URL: https://example.com/path
Phishing probability: 1.0000
Prediction: Phishing

URL: example.com/path
Phishing probability: 0.2272
Prediction: Benign

URL: https://[2001:db8::1]/login
Phishing probability: 1.0000
Prediction: Phishing

In [ ]:
url = "https://[2001:db8::1]/login"

print("URL:", url)
print("Python features:", extract_features(url))

URL: https://[2001:db8::1]/login
Python features: [27, 0, 0, 1, 0, 6, 3, 1]

In [ ]:

import json
from google.colab import files

# Upload the current Android model JSON file
uploaded = files.upload()

filename = next(iter(uploaded))

with open(filename, "r", encoding="utf-8") as file:
    model_data = json.load(file)

print("File loaded:", filename)
print("Top-level data type:", type(model_data).__name__)

if isinstance(model_data, dict):
    print("Top-level keys:", list(model_data.keys()))
    print("Sample structure:")
    print(json.dumps(model_data, indent=2)[:1500])
elif isinstance(model_data, list):
    print("Number of top-level items:", len(model_data))
    print("Sample structure:")
    print(json.dumps(model_data[:2], indent=2)[:1500])

Saving phishing_tree_final_cw3.json to phishing_tree_final_cw3 (1).json
File loaded: phishing_tree_final_cw3 (1).json
Top-level data type: dict
Top-level keys: ['children_left', 'children_right', 'features', 'thresholds', 'values']
Sample structure:
{
  "children_left": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    -1,
    -1,
    11,
    12,
    -1,
    -1,
    -1,
    16,
    -1,
    18,
    -1,
    -1,
    21,
    22,
    23,
    -1,
    -1,
    -1,
    -1,
    28,
    29,
    30,
    31,
    32,
    -1,
    -1,
    -1,
    36,
    37,
    38,
    -1,
    -1,
    -1,
    -1,
    -1,
    44,
    45,
    46,
    47,
    48,
    -1,
    -1,
    -1,
    52,
    -1,
    -1,
    55,
    56,
    -1,
    -1,
    59,
    60,
    -1,
    -1,
    -1,
    64,
    -1,
    66,
    -1,
    -1,
    69,
    70,
    71,
    72,
    73,
    74,
    -1,
    -1,
    77,
    -1,
    -1,
    80,
    81,
    -1,
    -1,
    -1,
    85,
    86,
    -1,
    -1,
    -1,
    90,
    91,
    92,
    93,
    94,
    -1,
    -1,
    -1,
    -1,
    99,
    100,
    -1,
    -1,
    103,
    104,
    -1,
    -1,
    -1,
    108,
    109,
    -1,
    -1,
    112,
    113,
    -1,
    -1,
    116,
    -1,
    -1,
    119,
    120,
    121,
    122,
    123,
    124,
    -1,
    -1,
    -1,
    128,
    -1,
    -1,
    131,
    132,
    133,
    -1,
    -1,
    136,
    -1,
    -1,
    139,
    140,
    -1,
    -1,
    143,
    -1,
    -1,
    146,
    147,
    148,
    -1,
    150,
    -1,
    -1,
    153,
    154,
    -1,
    -1,
    157,
    -1,
    -1,
    -1,
    161,
    162,
    163,
    164,
    -1,
    -1,
    167,
    -1,
    -1,
    170,
    171,
    -1,
    173,
    -1,
    -1,
    176,
    -1,
    -1,
    179,
    180,
    1

In [ ]:

# Verify the structure of the current TinyPhish model

left = model_data["children_left"]
right = model_data["children_right"]
features = model_data["features"]
thresholds = model_data["thresholds"]
values = model_data["values"]

# Count the nodes using the model arrays
node_count = len(left)

print("MODEL VERIFICATION RESULTS")
print("---------------------------")
print("Total nodes:", node_count)
print("Left-child entries:", len(left))
print("Right-child entries:", len(right))
print("Feature entries:", len(features))
print("Threshold entries:", len(thresholds))
print("Class-value entries:", len(values))

# Calculate the maximum depth, starting at the root node
def get_depth(node):
    if left[node] == -1 and right[node] == -1:
        return 0

    left_depth = get_depth(left[node]) if left[node] != -1 else 0
    right_depth = get_depth(right[node]) if right[node] != -1 else 0

    return 1 + max(left_depth, right_depth)

max_depth = get_depth(0)

print("Maximum depth:", max_depth)
print("Model file size:", len(json.dumps(model_data).encode("utf-8")), "bytes")

MODEL VERIFICATION RESULTS
---------------------------
Total nodes: 645
Left-child entries: 645
Right-child entries: 645
Feature entries: 645
Threshold entries: 645
Class-value entries: 645
Maximum depth: 10
Model file size: 33773 bytes

In [ ]:
tn = 6475
fp = 1395
fn = 227
tp = 18137

print("Total test samples:", tn + fp + fn + tp)
print("Benign samples:", tn + fp)
print("Phishing samples:", fn + tp)

Total test samples: 26234
Benign samples: 7870
Phishing samples: 18364